#!/usr/bin/env python3
"""ChunkSplitter.py

Reads rag-src/*.json (JSON files generated by Crawler.py), splits text and code
into chunks, and saves them to rag-src/chunk/{stem}-{idx:04d}.json.

NOTE: All .json files (input and output) contain JSON payloads, not plain text.
Output file format: JSON
  {url, title, lang, source_file, chunk_index, chunk_type, content}
  chunk_type: "text" or "code"

Pipeline position: Crawler.py → ChunkSplitter.py → RagIngester.py
"""

import argparse
import re
from pathlib import Path
from typing import NotRequired, TypedDict

import orjson
from rag.exceptions import ChunkFormatError
from rag.ingestion.chunk_english import ChunkEnglishMixin
from rag.ingestion.chunk_japanese import ChunkJapaneseMixin
from rag.ingestion.chunk_utils import merge_text_items
from rag.ingestion.pipeline_utils import (
    ChunkJsonRaw,
    collect_source_files,
    is_already_processed,
    read_json_file,
)
from rag.models_data import ChunkDocument
from shared.config_loader import ConfigLoader
from shared.logger import Logger
from sudachipy import dictionary as sudachi_dict
from sudachipy import tokenizer as sudachi_tok

MIN_HEADING_LINES_FOR_MARKDOWN = 2
MARKDOWN_HEADING_RE = r"^#{1,6}"

logger = Logger(__name__, "/opt/llm/logs/chunk.log")


class CrawlFilePayload(TypedDict):
    """Typed dict for crawl output JSON files."""

    url: str
    title: str
    lang: str
    content: str
    code_blocks: list[str]
    etag: NotRequired[str | None]
    last_modified: NotRequired[str | None]


class ChunkOutputPayload(TypedDict):
    """Typed dict for chunk output JSON files."""

    schema_version: str
    artifact_type: str
    created_by: str
    url: str
    title: str
    lang: str
    source_file: str
    chunk_index: int
    chunk_type: str
    content: str
    normalized_content: NotRequired[str | None]


class ChunkMetadata(TypedDict, total=False):
    """Typed dict for document-level metadata shared across chunk files.

    All fields are optional because this dict is spread with ** into the output payload.
    TypedDict spreading requires total=False and cannot be used in constructor calls.
    """

    url: str
    title: str
    lang: str
    etag: str | None
    last_modified: str | None
    source_file: str
    chunking_strategy: str


# ──────────────────────────────────────────────────────────────────────────────
# ChunkSplitter class
# ──────────────────────────────────────────────────────────────────────────────
class ChunkSplitter(ChunkEnglishMixin, ChunkJapaneseMixin):
    """Splits crawl output (rag-src/*.json JSON) into text and code chunks and writes them to rag-src/chunk/ for ingestion."""

    def __init__(self, config: dict | None = None) -> None:
        """Initialize the chunk splitter with configuration from TOML file or provided dict."""
        cfg: dict = config or ConfigLoader().load("chunk_splitter.toml")
        rag_src_dir = Path(cfg["rag_src_dir"])
        self._chunk_dir: Path = rag_src_dir / "chunk"
        self._min_chunk: int = int(cfg["min_chunk"])
        self._max_chunk: int = int(cfg["max_chunk"])
        self._en_stopwords: frozenset[str] = frozenset(cfg["en_stopwords"])
        self._ja_stop_pos: frozenset[str] = frozenset(cfg["ja_stop_pos"])
        self._chunk_overlap: int = int(cfg.get("chunk_overlap", 50))
        # Markdown heading-based snippet mode: split on # / ## / ### boundaries
        self._md_index_enable: bool = bool(cfg.get("md_index_enable", False))
        self._md_snippet_max_chars: int = int(cfg.get("md_snippet_max_chars", 600))
        self._rag_src_dir: Path = rag_src_dir
        # SplitMode.C: longest compound unit; optimal for NLP downstream tasks
        sd_dict = sudachi_dict.Dictionary(dict="core")
        self._sd_tkn = sd_dict.create()
        self._split_c = sudachi_tok.Tokenizer.SplitMode.C

    # ── Public interface ──────────────────────────────────────────────────────

    def process_all(self, target: Path | None = None, force: bool = False) -> int:
        """Process all *.json files in rag-src/ (or a single target); returns total chunks written."""
        paths = self._collect_targets(target)
        if not paths:
            logger.info("No source files to process")
            return 0
        total = 0
        for path in paths:
            try:
                total += self.process_file(path, force)
            except (OSError, RuntimeError, ValueError) as e:
                logger.exception("process_file failed: %s: %s", path, e)
        logger.info("=== done: %s chunks from %s files ===", total, len(paths))
        return total

    def process_file(self, src_path: Path, force: bool = False) -> int:
        """Read a crawler JSON file, split into chunks, and write to chunk_dir; returns chunk count; skips already-chunked files when force=False."""
        if not src_path.exists():
            logger.error("Source file does not exist: %s", src_path)
            return 0
        sentinel = self._chunk_dir / f"{src_path.stem}-0000.json"
        if is_already_processed(sentinel, force):
            chunk_doc = self._read_source_data(src_path)
            if chunk_doc is not None:
                logger.info(
                    "skip (already chunked)",
                    extra={"url": chunk_doc.url},
                )
            return 0
        chunk_doc = self._read_source_data(src_path)
        if chunk_doc is None:
            return 0
        chunks = self._build_chunk_list(chunk_doc)
        chunking_strategy = "heading" if self._is_markdown_source(chunk_doc) else "text"
        written = self._write_chunk_files(
            chunks, chunk_doc, src_path, chunking_strategy
        )
        logger.info(
            "chunked %s chunks from %s",
            written,
            src_path.name,
            extra={"url": chunk_doc.url},
        )
        return written

    # ── English and Japanese chunking ─────────────────────────────────────────
    # Provided by ChunkEnglishMixin and ChunkJapaneseMixin respectively.
    # ─────────────────────────────────────────────────────────────────────────

    # ── Markdown heading chunking ──────────────────────────────────────────────

    def _is_markdown_source(self, data: ChunkDocument | ChunkJsonRaw) -> bool:
        """Return True when the source should use heading-based snippet chunking.

        .md / .markdown / .mdx files always use heading chunking regardless of md_index_enable.
        Non-.md files use heuristic detection only when md_index_enable is set.
        """
        url = data.url if isinstance(data, ChunkDocument) else data.get("url", "")
        if not isinstance(url, str):
            return False
        if url.endswith((".md", ".markdown", ".mdx")):
            return True
        if not self._md_index_enable:
            return False
        content = (
            data.content if isinstance(data, ChunkDocument) else data.get("content", "")
        )
        if not isinstance(content, str):
            return False
        return (
            len(re.findall(rf"{MARKDOWN_HEADING_RE} .+", content, re.MULTILINE))
            >= MIN_HEADING_LINES_FOR_MARKDOWN
        )

    def _chunk_markdown_by_heading(self, text: str) -> list[str]:
        """Split Markdown text at heading boundaries into snippet chunks; sections exceeding md_snippet_max_chars are further split via _chunk_english."""
        # Split before each heading line; keep the heading with its section
        sections = re.split(
            rf"(?={MARKDOWN_HEADING_RE} )", text.strip(), flags=re.MULTILINE
        )
        chunks: list[str] = []
        for section in sections:
            section = section.strip()
            if not section:
                continue
            if len(section) <= self._md_snippet_max_chars:
                if len(section) >= self._min_chunk:
                    chunks.append(section)
            else:
                # Section too large; fall back to sentence-level chunking
                chunks.extend(self._chunk_english(section))
        return chunks

    # ── Code chunking ─────────────────────────────────────────────────────────

    def _chunk_code(self, code: str) -> list[str]:
        """Split a code block at blank lines (function/class boundaries); not subject to stopword removal or morphological analysis."""
        blocks = re.split(r"\n{2,}", code.strip())
        chunks: list[str] = merge_text_items(
            blocks,
            "\n\n",
            self._min_chunk,
            self._max_chunk,
            self._chunk_overlap,
        )
        return chunks

    # ── File I/O ──────────────────────────────────────────────────────────────

    def _read_source_data(self, src_path: Path) -> ChunkDocument | None:
        """Read and parse a JSON crawl file; returns ChunkDocument or None on failure."""
        try:
            return read_json_file(src_path)
        except (FileNotFoundError, ChunkFormatError) as e:
            logger.error("skip %s: %s", src_path.name, e)
            return None

    def _build_chunk_list(self, data: ChunkDocument) -> list[tuple[str, str, str]]:
        """Extract content from a crawl record and split into (chunk_type, content, normalized_content) triples; normalized populated only for Japanese text."""
        lang = data.lang
        content = data.content
        code_blocks = data.code_blocks

        text_triples: list[tuple[str, str, str]] = self._build_text_triples(
            data, lang, content
        )
        code_triples: list[tuple[str, str, str]] = self._build_code_triples(code_blocks)

        return text_triples + code_triples

    def _build_text_triples(
        self, data: ChunkDocument, lang: str, content: str
    ) -> list[tuple[str, str, str]]:
        """Build text triples from content; delegates to markdown/English/Japanese chunkers."""
        if not content:
            return []
        if self._is_markdown_source(data):
            return [("text", c, "") for c in self._chunk_markdown_by_heading(content)]
        if lang == "ja":
            return [
                ("text", orig, norm) for orig, norm in self._chunk_japanese(content)
            ]
        return [("text", c, "") for c in self._chunk_english(content)]

    def _build_code_triples(self, code_blocks: list[str]) -> list[tuple[str, str, str]]:
        """Build code triples from each code block independently."""
        return [("code", c, "") for cb in code_blocks for c in self._chunk_code(cb)]

    def _write_chunk_files(
        self,
        chunks: list[tuple[str, str, str]],
        data: ChunkDocument,
        src_path: Path,
        chunking_strategy: str = "text",
    ) -> int:
        """Write (chunk_type, content, normalized_content) triples to chunk_dir."""
        if not chunks:
            return 0
        self._chunk_dir.mkdir(parents=True, exist_ok=True)
        metadata = self._extract_chunk_metadata(data, src_path, chunking_strategy)
        written: int = 0
        for idx, (chunk_type, chunk_content, norm_content) in enumerate(chunks):
            out_path = self._chunk_dir / f"{src_path.stem}-{idx:04d}.json"
            payload = self._build_chunk_payload(
                metadata, idx, chunk_type, chunk_content, norm_content
            )
            try:
                out_path.write_bytes(
                    orjson.dumps(payload, option=orjson.OPT_INDENT_2),
                )
                written += 1
            except OSError as e:
                logger.error("failed to write chunk %s: %s", out_path, e)
        return written

    def _extract_chunk_metadata(
        self, data: ChunkDocument, src_path: Path, chunking_strategy: str
    ) -> ChunkMetadata:
        """Extract document-level metadata shared across all chunk files."""
        return {
            "url": data.url,
            "title": data.title,
            "lang": data.lang,
            "etag": data.etag,
            "last_modified": data.last_modified,
            "source_file": src_path.name,
            "chunking_strategy": chunking_strategy,
        }

    def _build_chunk_payload(
        self,
        metadata: ChunkMetadata,
        idx: int,
        chunk_type: str,
        chunk_content: str,
        norm_content: str | None,
    ) -> dict[str, object]:
        """Build a single chunk JSON payload from shared metadata and chunk-specific fields."""
        return {
            "schema_version": "1",
            "artifact_type": "chunk",
            "created_by": "chunk_splitter",
            **metadata,
            "chunk_index": idx,
            "chunk_type": chunk_type,
            "content": chunk_content,
            "normalized_content": norm_content or None,
        }

    def _collect_targets(self, target: Path | None) -> list[Path]:
        """Return source files to process. Delegates to pipeline_utils."""
        files, _ = collect_source_files(self._rag_src_dir, target)
        result: list[Path] = files
        return result


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────
def main() -> None:
    """CLI entry point for chunking rag-src JSON files into document chunks."""
    parser = argparse.ArgumentParser(
        description="Chunking: rag-src/*.json → rag-src/chunk/{stem}-{idx:04d}.json",
    )
    parser.add_argument(
        "--file",
        help="Process a single file (default: process all files in rag-src/*.json)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-process even if output chunks already exist",
    )
    args = parser.parse_args()

    target: Path | None = None
    if args.file:
        target = Path(args.file)
        if not target.exists():
            parser.error(f"File does not exist: {target}")

    splitter = ChunkSplitter()
    splitter.process_all(target, args.force)


if __name__ == "__main__":
    from shared.config_loader import ConfigLoader

    ConfigLoader.restrict_to("chunk_splitter.toml")
    main()
