#!/usr/bin/env python3
"""RagIngester.py
Reads rag-src/chunk/*.txt (JSON files generated by ChunkSplitter.py),
generates embeddings, and ingests them into SQLite (documents / chunks / chunks_vec).
Processed files are moved to rag-src/registered/.

NOTE: All .txt files consumed here contain JSON payloads, not plain text.
Parse with orjson.loads() or json.loads(); do not treat as UTF-8 text.

Pipeline position: Crawler.py → ChunkSplitter.py → RagIngester.py
"""

import argparse
import dataclasses
import shutil
import sqlite3
import time
from collections import defaultdict
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, NotRequired, TypedDict

import httpx
import orjson
from db.helper import SQLiteHelper
from db.maintenance import (
    RagConsistencyReport,
    check_rag_consistency,
    is_consistent,
)
from rag.ingestion.pipeline_utils import _read_chunk_json_raw
from rag.utils import floats_to_blob, validate_url
from shared.config_loader import ConfigLoader
from shared.logger import Logger

logger = Logger(__name__, "/opt/llm/logs/ingest.log")


class ChunkData(TypedDict):
    """Typed dict for chunk JSON payload fields."""

    url: str
    title: NotRequired[str]
    lang: NotRequired[str]
    content: str
    code_blocks: NotRequired[list[str]]
    etag: NotRequired[str | None]
    last_modified: NotRequired[str | None]
    chunking_strategy: NotRequired[str]
    normalized_content: NotRequired[str | None]
    chunk_index: NotRequired[int]
    source_file: NotRequired[str]
    chunk_type: NotRequired[str]
    artifact_type: NotRequired[str]


# ChunkData type for ** spreading (cannot use TypedDict in constructor calls)
_ChunkDataDict = dict[str, Any]


@dataclasses.dataclass(frozen=True)
class IngestUrlResult:
    """Per-URL ingestion outcome returned by ingest_url_group()."""

    url: str
    n_success: int
    n_failed: int
    skipped: bool
    n_embed_failed: int = 0  # embedding failures (separate from parse/DB failures)


# Accepted lang values enforced by the documents.lang CHECK constraint
_VALID_LANGS: frozenset[str] = frozenset({"en", "ja"})


def delete_document_chain(db: SQLiteHelper, doc_id: int) -> None:
    """Delete chunks_vec → chunks → documents for doc_id.

    chunks_vec has no FK to chunks, so it must be deleted first.
    chunks deletion fires FTS5 triggers automatically (via ON DELETE trigger on chunks).
    documents deletion cascades to any remaining chunks rows.
    """
    db.execute(
        "DELETE FROM chunks_vec"
        " WHERE chunk_id IN (SELECT chunk_id FROM chunks WHERE doc_id = ?)",
        (doc_id,),
    )
    db.execute("DELETE FROM chunks WHERE doc_id = ?", (doc_id,))
    db.execute("DELETE FROM documents WHERE doc_id = ?", (doc_id,))


# ──────────────────────────────────────────────────────────────────────────────
# RagIngester class
# ──────────────────────────────────────────────────────────────────────────────
class RagIngester:
    """Embeds chunk files produced by ChunkSplitter and inserts them into SQLite; chunks are grouped by URL and moved to registered/ after ingestion."""

    def __init__(self, config: dict | None = None) -> None:
        cfg: dict = config or {
            **ConfigLoader().load_all(),
            **ConfigLoader().load("rag_pipeline.toml"),
        }
        rag_src_dir = Path(cfg["rag_src_dir"])
        self._chunk_dir: Path = rag_src_dir / "chunk"
        self._registered_dir: Path = rag_src_dir / "registered"
        self._embed_url: str = cfg["embed_url"]
        self._embed_retry: int = int(cfg["embed_retry"])
        self._embed_workers: int = int(cfg.get("embed_workers", 4))
        self._expected_dims: int = int(cfg.get("embedding_dims", 384))
        self._client = httpx.Client(timeout=60)

    def close(self) -> None:
        """Close the underlying HTTP client."""
        self._client.close()

    def __del__(self) -> None:
        try:
            self._client.close()
        except OSError:
            pass

    # ── Public interface ──────────────────────────────────────────────────────

    def ingest_all(
        self,
        force: bool = False,
        on_ingest_complete: Callable[[], None] | None = None,
    ) -> RagConsistencyReport | None:
        """Process all chunk files in chunk_dir grouped by URL; force=True deletes existing document records before re-inserting.

        Returns the post-ingestion consistency report, or None if the check failed.
        Callers that do not inspect the return value are unaffected.
        """
        chunk_files = sorted(self._chunk_dir.glob("*.json"))
        if not chunk_files:
            logger.info("No chunk files to process")
            return None
        url_groups = self._group_chunks_by_url(chunk_files)
        with SQLiteHelper().open(write_mode=True) as db:
            results = self._process_url_groups(db, url_groups, force)
        total_success = sum(r.n_success for r in results)
        total_failed = sum(r.n_failed for r in results if r.n_failed > 0)
        total_embed_failed = sum(
            r.n_embed_failed for r in results if r.n_embed_failed > 0
        )
        total_skipped = sum(1 for r in results if r.skipped)
        logger.info(
            "=== done: %s URLs processed (%d success, %d failed, %d embed-failed, %d skipped) ===",
            len(results),
            total_success,
            total_failed,
            total_embed_failed,
            total_skipped,
            extra={"stage_name": "ingester"},
        )
        try:
            report = check_rag_consistency(db, embed_failed=total_embed_failed)
            if not is_consistent(report):
                for issue in report.issues:
                    logger.warning(
                        "Post-ingest consistency: %s",
                        issue,
                        extra={"stage_name": "ingester"},
                    )
            if on_ingest_complete is not None:
                try:
                    on_ingest_complete()
                except (TypeError, ValueError):
                    logger.exception("on_ingest_complete callback failed")
            return report
        except (sqlite3.OperationalError, sqlite3.DatabaseError, ValueError):
            logger.exception("Post-ingest consistency check failed")
            return None

    def ingest_url_group(
        self,
        db: SQLiteHelper,
        url: str,
        chunk_files: list[Path],
        force: bool,
    ) -> IngestUrlResult:
        """Ingest all chunk files for one URL into SQLite in ascending chunk_index order; moves files to registered/ after processing including on skip."""
        if not chunk_files:
            src_type = "file" if url.startswith("file://") else "http"
            logger.warning(
                "No chunk files provided for URL: %s",
                url,
                extra={"source_type": src_type, "stage_name": "ingester"},
            )
            return IngestUrlResult(url=url, n_success=0, n_failed=0, skipped=True)
        chunk_files = sorted(chunk_files, key=lambda p: p.stem)
        first_data = self._read_chunk_json(chunk_files[0])
        if first_data is None:
            return IngestUrlResult(
                url=url, n_success=0, n_failed=len(chunk_files), skipped=False
            )
        try:
            self._validate_artifact(first_data, "chunk")
        except ValueError as e:
            src_type = "file" if url.startswith("file://") else "http"
            logger.error(
                "artifact validation failed for %s: %s",
                url,
                e,
                extra={"source_type": src_type, "stage_name": "ingester"},
            )
            return IngestUrlResult(
                url=url, n_success=0, n_failed=len(chunk_files), skipped=False
            )
        title: str = first_data.get("title", "")
        lang: str = first_data.get("lang", "en")
        etag: str | None = first_data.get("etag")
        last_modified: str | None = first_data.get("last_modified")
        fetched_at: str | None = first_data.get("fetched_at")
        chunking_strategy: str = first_data.get("chunking_strategy", "text")
        doc_id = self._get_or_create_document(
            db,
            url,
            title,
            lang,
            force,
            etag,
            last_modified,
            chunking_strategy,
            fetched_at=fetched_at,
        )
        if doc_id is None:
            logger.info(
                "already registered, skipping",
                extra={"url": url},
            )
            self._move_to_registered(chunk_files)
            return IngestUrlResult(url=url, n_success=0, n_failed=0, skipped=True)
        # Commit document record before parallel chunk inserts (FK dependency).
        db.commit()
        inserted, failed, embed_failed = self._ingest_chunk_files(doc_id, chunk_files)
        src_type = "file" if url.startswith("file://") else "http"
        logger.info(
            "inserted %s/%s chunks (%s failed, %s embed-failed): %s",
            inserted,
            len(chunk_files),
            failed,
            embed_failed,
            url,
            extra={"doc_id": doc_id, "source_type": src_type, "stage_name": "ingester"},
        )
        self._move_to_registered(chunk_files)
        return IngestUrlResult(
            url=url,
            n_success=inserted,
            n_failed=failed,
            skipped=False,
            n_embed_failed=embed_failed,
        )

    # ── Embedding ─────────────────────────────────────────────────────────────

    def _get_embedding(self, text: str) -> list[float] | None:
        """Return embedding vector for text; validates dimension against embedding_dims config.

        Returns None on empty input, network failure, or dimension mismatch.
        Expected dimension is read from common.toml::embedding_dims (default 384).
        """
        if not text or not text.strip():
            return None
        for attempt in range(self._embed_retry):
            try:
                resp = self._client.post(
                    self._embed_url,
                    # E5 passage prefix is mandatory for document-side embedding
                    json={"content": f"passage: {text}"},
                )
                resp.raise_for_status()
                embedding = orjson.loads(resp.content).get("embedding")
                if not isinstance(embedding, list) or not embedding:
                    raise ValueError("missing or empty 'embedding' field in response")
                if len(embedding) != self._expected_dims:
                    raise ValueError(
                        f"embedding dimension mismatch: expected {self._expected_dims},"
                        f" got {len(embedding)}"
                    )
                return embedding
            except (
                httpx.RequestError,
                httpx.HTTPStatusError,
                orjson.JSONDecodeError,
                ValueError,
            ) as e:
                logger.warning(
                    "embedding attempt %s/%s: %s",
                    attempt + 1,
                    self._embed_retry,
                    e,
                )
                if attempt < self._embed_retry - 1:
                    time.sleep(min(2**attempt, 10))
        return None

    # ── Document helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _validate_artifact(payload: _ChunkDataDict, expected_type: str) -> None:
        """Validate artifact_type field; lenient for backward compatibility (missing artifact_type is accepted)."""
        actual = payload.get("artifact_type")
        if actual is not None and actual != expected_type:
            raise ValueError(
                f"Expected artifact_type={expected_type!r}, got {actual!r}"
            )

    @staticmethod
    def _is_file_unchanged(
        existing_etag: str | None,
        existing_last_modified: str | None,
        new_etag: str | None,
        new_last_modified: str | None,
    ) -> bool:
        """Return True when the file SHA-256 hash is unchanged."""
        if existing_etag is None or new_etag is None:
            return False
        return existing_etag == new_etag

    def _delete_existing_document(self, db: SQLiteHelper, doc_id: int) -> None:
        """Delete a document and its chunks; chunks_vec removed first because it has no FK constraint to chunks."""
        delete_document_chain(db, doc_id)

    def _update_etag(
        self,
        db: SQLiteHelper,
        doc_id: int,
        etag: str | None,
        last_modified: str | None,
        new_fetched_at: str | None = None,
    ) -> None:
        """Refresh ETag/Last-Modified for an existing document (skip-case).

        Guards against stale overwrites: if new_fetched_at < stored fetched_at,
        the incoming data is older and the existing DB values are kept.
        """
        if etag is None and last_modified is None:
            return
        if self._is_stale_update(db, doc_id, new_fetched_at):
            logger.info(
                "skip-path etag update skipped: incoming stale (%s < %s) for doc_id=%d",
                new_fetched_at,
                doc_id,
                extra={"stage_name": "ingester"},
            )
            return
        if new_fetched_at is not None:
            self._update_etag_with_freshness(
                db, doc_id, etag, last_modified, new_fetched_at
            )
        else:
            self._update_etag_null_fill(db, doc_id, etag, last_modified)
        self._log_etag_updated(doc_id)

    def _is_stale_update(
        self, db: SQLiteHelper, doc_id: int, new_fetched_at: str | None
    ) -> bool:
        """Return True when the incoming data is older than stored fetched_at."""
        if new_fetched_at is None:
            return False
        rows = db.fetchall(
            "SELECT fetched_at FROM documents WHERE doc_id = ?", (doc_id,)
        )
        stored_fetched_at = rows[0][0] if rows else None
        return bool(stored_fetched_at and new_fetched_at < stored_fetched_at)

    def _update_etag_with_freshness(
        self,
        db: SQLiteHelper,
        doc_id: int,
        etag: str | None,
        last_modified: str | None,
        fetched_at: str,
    ) -> None:
        """Overwrite ETag/Last-Modified when freshness is proven."""
        db.execute(
            "UPDATE documents SET etag = ?, last_modified = ?,"
            " fetched_at = COALESCE(?, fetched_at) WHERE doc_id = ?",
            (etag, last_modified, fetched_at, doc_id),
        )
        db.commit()

    def _update_etag_null_fill(
        self, db: SQLiteHelper, doc_id: int, etag: str | None, last_modified: str | None
    ) -> None:
        """Fill NULL only; never overwrite existing values."""
        db.execute(
            "UPDATE documents SET etag = COALESCE(etag, ?), last_modified = COALESCE(last_modified, ?)"
            " WHERE doc_id = ?",
            (etag, last_modified, doc_id),
        )
        db.commit()

    def _log_etag_updated(self, doc_id: int) -> None:
        """Log the etag update."""
        logger.info(
            "skip-path etag updated for doc_id=%d",
            doc_id,
            extra={"stage_name": "ingester"},
        )

    def _validate_lang(self, lang: str) -> bool:
        """Return True when lang is a valid value."""
        return lang in _VALID_LANGS

    def _handle_existing_document(
        self,
        db: SQLiteHelper,
        url: str,
        existing_doc_id: int,
        force: bool,
        etag: str | None,
        last_modified: str | None,
        fetched_at: str | None,
    ) -> bool:
        """Handle an existing document; return True when the caller should skip insertion."""
        if not force and url.startswith("file://"):
            return self._handle_existing_file(
                db, url, existing_doc_id, etag, last_modified
            )
        if not force:
            self._update_etag(db, existing_doc_id, etag, last_modified, fetched_at)
            return True
        return False

    def _handle_existing_file(
        self,
        db: SQLiteHelper,
        url: str,
        existing_doc_id: int,
        etag: str | None,
        last_modified: str | None,
    ) -> bool:
        """Handle an existing file:// document; return True when unchanged."""
        stored = db.execute(
            "SELECT etag, last_modified FROM documents WHERE doc_id = ?",
            (existing_doc_id,),
        ).fetchone()
        if stored and self._is_file_unchanged(
            stored["etag"], stored["last_modified"], etag, last_modified
        ):
            logger.info(
                "file:// unchanged (sha256 match): %s",
                url,
                extra={"stage_name": "ingester"},
            )
            return True
        logger.info(
            "file:// changed — auto re-ingesting: %s",
            url,
            extra={"stage_name": "ingester"},
        )
        return False

    def _get_or_create_document(
        self,
        db: SQLiteHelper,
        url: str,
        title: str,
        lang: str,
        force: bool,
        etag: str | None = None,
        last_modified: str | None = None,
        chunking_strategy: str = "text",
        fetched_at: str | None = None,
    ) -> int | None:
        """Register a URL in documents and return its doc_id; returns None when already registered and force=False; force=True deletes existing record first."""
        if not self._validate_lang(lang):
            raise ValueError(
                f"unsupported lang value: {lang!r}"
                f" (must be one of {sorted(_VALID_LANGS)})",
            )
        existing_row = db.execute(
            "SELECT doc_id FROM documents WHERE url = ?",
            (url,),
        ).fetchone()
        if existing_row:
            existing_doc_id: int = existing_row[0]
            if self._handle_existing_document(
                db, url, existing_doc_id, force, etag, last_modified, fetched_at
            ):
                return None
            self._delete_existing_document(db, existing_doc_id)
        cur = db.execute(
            "INSERT INTO documents"
            " (url, title, lang, etag, last_modified, chunking_strategy)"
            " VALUES (?, ?, ?, ?, ?, ?)",
            (url, title, lang, etag, last_modified, chunking_strategy),
        )
        return cur.lastrowid

    def _insert_chunk(
        self,
        db: SQLiteHelper,
        doc_id: int,
        idx: int,
        content: str,
        normalized_content: str | None,
        embedding: list[float],
        chunk_type: str = "",
        source_file: str = "",
    ) -> None:
        """Insert a chunk and its embedding vector; chunks_fts synced via trigger using COALESCE(normalized_content, content); embedding stored as float32 BLOB."""
        cur = db.execute(
            "INSERT INTO chunks (doc_id, chunk_index, content, normalized_content, chunk_type, source_file)"
            " VALUES (?, ?, ?, ?, ?, ?)",
            (doc_id, idx, content, normalized_content or None, chunk_type, source_file),
        )
        chunk_id = cur.lastrowid
        db.execute(
            "INSERT INTO chunks_vec (chunk_id, embedding) VALUES (?, ?)",
            (chunk_id, floats_to_blob(embedding)),
        )

    # ── Bulk file processing ──────────────────────────────────────────────────

    def _read_chunk_json(self, path: Path) -> _ChunkDataDict | None:
        """Read and parse a chunk JSON file as a raw dict; returns None on failure."""
        return _read_chunk_json_raw(path)

    def _embed_and_store(self, doc_id: int, path: Path) -> tuple[bool, bool]:
        """Embed one chunk and insert it using an independent DB connection; each call opens its own connection for safe parallel writes.

        Returns (chunk_ok, embed_ok).
        chunk_ok=False means total failure (parse/DB error or embed failure).
        embed_ok=False specifically means embedding failed (content was valid).
        """
        data = self._read_chunk_json(path)
        if data is None:
            return False, False
        try:
            self._validate_artifact(data, "chunk")
        except ValueError:
            logger.warning(
                "artifact validation failed for %s",
                path.name,
                extra={"source_type": "file", "stage_name": "ingester"},
            )
            return False, False
        content: str = data.get("content", "")
        nc_raw = data.get("normalized_content")
        normalized_content: str | None = (
            nc_raw if isinstance(nc_raw, str) and nc_raw else None
        )
        idx_raw = data.get("chunk_index", 0)
        try:
            idx = int(idx_raw)
        except (ValueError, TypeError) as e:
            logger.warning(
                "Invalid chunk_index in %s: %s, using 0",
                path.name,
                e,
                extra={
                    "doc_id": doc_id,
                    "source_type": "file",
                    "stage_name": "ingester",
                },
            )
            idx = 0
        chunk_type: str = data.get("chunk_type", "") or ""
        source_file: str = data.get("source_file", "") or ""
        # Embed original content; E5 understands raw Japanese.
        # normalized_content is for FTS only and not used for embedding.
        embedding = self._get_embedding(content)
        if embedding is None:
            chunk_url = data.get("url", "")
            logger.warning(
                "embedding failed for %s: %r",
                path.name,
                content[:60],
                extra={
                    "doc_id": doc_id,
                    "url": chunk_url,
                    "source_type": "file",
                    "stage_name": "ingester",
                },
            )
            return False, False
        with SQLiteHelper().open(write_mode=True) as db:
            self._insert_chunk(
                db,
                doc_id,
                idx,
                content,
                normalized_content,
                embedding,
                chunk_type,
                source_file,
            )
            db.commit()
        return True, True

    def _ingest_chunk_files(
        self, doc_id: int, chunk_files: list[Path]
    ) -> tuple[int, int, int]:
        """Embed and insert chunk files in parallel via ThreadPoolExecutor; returns (n_inserted, n_failed, n_embed_failed)."""
        inserted = 0
        failed = 0
        embed_failed = 0
        with ThreadPoolExecutor(max_workers=self._embed_workers) as executor:
            futures = {
                executor.submit(self._embed_and_store, doc_id, path): path
                for path in chunk_files
            }
            for future in as_completed(futures):
                path = futures[future]
                try:
                    chunk_ok, embed_ok = future.result()
                    if chunk_ok:
                        inserted += 1
                    else:
                        failed += 1
                        if not embed_ok:
                            embed_failed += 1
                except (
                    httpx.HTTPStatusError,
                    httpx.RequestError,
                    OSError,
                    ValueError,
                    TypeError,
                ) as e:
                    chunk_data = self._read_chunk_json(path)
                    chunk_url = chunk_data.get("url", "") if chunk_data else ""
                    logger.error(
                        "Failed to ingest %s: %s",
                        path,
                        e,
                        extra={
                            "doc_id": doc_id,
                            "url": chunk_url,
                            "source_type": "file",
                            "stage_name": "ingester",
                        },
                    )
                    failed += 1
        return inserted, failed, embed_failed

    def _group_chunks_by_url(self, chunk_files: list[Path]) -> dict[str, list[Path]]:
        """Group chunk files by URL read from their JSON 'url' field."""
        url_groups: dict[str, list[Path]] = defaultdict(list)
        for path in chunk_files:
            data = self._read_chunk_json(path)
            if data is None:
                continue
            url: str = data.get("url", "")
            if not url:
                logger.warning(
                    "url field missing: %s",
                    path.name,
                    extra={"source_type": "file", "stage_name": "ingester"},
                )
                continue
            # Accept file:// URLs from local file ingestion in addition to http/https
            if not validate_url(url) and not url.startswith("file://"):
                logger.warning(
                    "invalid url %r in %s, skipping",
                    url,
                    path.name,
                    extra={"source_type": "file", "stage_name": "ingester"},
                )
                continue
            url_groups[url].append(path)
        return url_groups

    def _process_url_groups(
        self,
        db: SQLiteHelper,
        url_groups: dict[str, list[Path]],
        force: bool,
    ) -> list[IngestUrlResult]:
        """Iterate over URL groups and ingest each; log exceptions without stopping."""
        results: list[IngestUrlResult] = []
        for url, paths in url_groups.items():
            try:
                results.append(self.ingest_url_group(db, url, paths, force))
            except (OSError, RuntimeError, ValueError, sqlite3.OperationalError):
                logger.exception("ingest_url_group failed: %s", url)
                results.append(
                    IngestUrlResult(url=url, n_success=0, n_failed=-1, skipped=False)
                )
        return results

    def _move_to_registered(self, paths: list[Path]) -> None:
        """Move ingested chunk files to registered/."""
        self._registered_dir.mkdir(parents=True, exist_ok=True)
        for path in paths:
            dest = self._registered_dir / path.name
            try:
                shutil.move(str(path), str(dest))
            except OSError as e:
                chunk_data = self._read_chunk_json(path)
                chunk_url = chunk_data.get("url", "") if chunk_data else ""
                logger.error(
                    "move failed %s → %s: %s",
                    path,
                    dest,
                    e,
                    extra={
                        "url": chunk_url,
                        "source_type": "file",
                        "stage_name": "ingester",
                    },
                )


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Embedding generation and DB ingestion:"
            " rag-src/chunk/*.txt → SQLite → rag-src/registered/"
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Force delete and re-ingest already registered URLs",
    )
    args = parser.parse_args()

    ingester = RagIngester()
    ingester.ingest_all(args.force)


if __name__ == "__main__":
    main()
