#!/usr/bin/env python3
"""RagIngester.py
Reads rag-src/chunk/*.json (JSON files generated by ChunkSplitter.py),
generates embeddings, and ingests them into SQLite (documents / chunks / chunks_vec).
Processed files are moved to rag-src/registered/.

NOTE: All .json files consumed here contain JSON payloads, not plain text.
Parse with orjson.loads() or json.loads(); do not treat as UTF-8 text.

Pipeline position: Crawler.py → ChunkSplitter.py → RagIngester.py
"""

import argparse
import dataclasses
import shutil
import sqlite3
import time
from collections import defaultdict
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import httpx
import orjson
from db.helper import SQLiteHelper
from db.models import RagConsistencyReport
from rag.ingestion.document_manager import DocumentManager
from rag.ingestion.pipeline_utils import ChunkJsonRaw, _read_chunk_json_raw
from rag.utils import floats_to_blob, validate_url
from shared.config_loader import ConfigLoader
from shared.logger import Logger

logger = Logger(__name__, "/opt/llm/logs/ingest.log")


@dataclasses.dataclass(frozen=True)
class IngestUrlResult:
    """Per-URL ingestion outcome returned by ingest_url_group()."""

    url: str
    n_success: int
    n_failed: int
    skipped: bool
    n_embed_failed: int = 0  # embedding failures (separate from parse/DB failures)


# Accepted lang values enforced by the documents.lang CHECK constraint
_VALID_LANGS: frozenset[str] = frozenset({"en", "ja"})


# ──────────────────────────────────────────────────────────────────────────────
# RagIngester class
# ──────────────────────────────────────────────────────────────────────────────
class RagIngester:
    """Embeds chunk files produced by ChunkSplitter and inserts them into SQLite; chunks are grouped by URL and moved to registered/ after ingestion."""

    def __init__(self, config: dict | None = None) -> None:
        cfg: dict = config or ConfigLoader().load("ingester.toml")
        rag_src_dir = Path(cfg["rag_src_dir"])
        self._chunk_dir: Path = rag_src_dir / "chunk"
        self._registered_dir: Path = rag_src_dir / "registered"
        self._embed_url: str = cfg["embed_url"]
        self._embed_retry: int = int(cfg["embed_retry"])
        self._embed_workers: int = int(cfg.get("embed_workers", 4))
        self._expected_dims: int = int(cfg.get("embedding_dims", 384))
        self._strict_artifact_validation: bool = bool(
            cfg.get("strict_artifact_validation", False)
        )
        # DB settings stored explicitly to bypass build_db_config() / agent.toml
        self._rag_db_path: str = str(cfg.get("rag_db_path", ""))
        self._sqlite_vec_so: str = str(cfg.get("sqlite_vec_so", ""))
        self._sqlite_timeout: int = int(cfg.get("sqlite_timeout", 30))
        self._sqlite_busy_timeout_ms: int = int(
            cfg.get("sqlite_busy_timeout_ms", 30000)
        )
        self._client = httpx.Client(timeout=60)

    def close(self) -> None:
        """Close the underlying HTTP client."""
        self._client.close()

    def __del__(self) -> None:
        try:
            client = getattr(self, "_client", None)
            if client is not None:
                client.close()
        except OSError:
            pass

    # ── Public interface ──────────────────────────────────────────────────────

    def ingest_all(
        self,
        force: bool = False,
        on_ingest_complete: Callable[[], None] | None = None,
    ) -> RagConsistencyReport | None:
        """Process all chunk files in chunk_dir grouped by URL; force=True deletes existing document records before re-inserting.

        Returns the post-ingestion consistency report, or None if the check failed.
        Callers that do not inspect the return value are unaffected.
        """
        chunk_files = sorted(self._chunk_dir.glob("*.json"))
        if not chunk_files:
            logger.info("No chunk files to process")
            return None
        url_groups = self._group_chunks_by_url(chunk_files)
        with SQLiteHelper(
            db_path=self._rag_db_path,
            sqlite_vec_so=self._sqlite_vec_so,
            sqlite_timeout=self._sqlite_timeout,
            sqlite_busy_timeout_ms=self._sqlite_busy_timeout_ms,
        ).open(write_mode=True) as db:
            doc_mgr = DocumentManager(db)
            results = self._process_url_groups(doc_mgr, db, url_groups, force)
        total_success = sum(r.n_success for r in results)
        total_failed = sum(r.n_failed for r in results if r.n_failed > 0)
        total_embed_failed = sum(
            r.n_embed_failed for r in results if r.n_embed_failed > 0
        )
        total_skipped = sum(1 for r in results if r.skipped)
        logger.info(
            "=== done: %s URLs processed (%d success, %d failed, %d embed-failed, %d skipped) ===",
            len(results),
            total_success,
            total_failed,
            total_embed_failed,
            total_skipped,
            extra={"stage_name": "ingester"},
        )
        return doc_mgr.check_consistency(
            embed_failed=total_embed_failed,
            on_ingest_complete=on_ingest_complete,
        )

    def ingest_url_group(
        self,
        doc_mgr: DocumentManager,
        db: SQLiteHelper,
        url: str,
        chunk_files: list[Path],
        force: bool,
    ) -> IngestUrlResult:
        """Ingest all chunk files for one URL into SQLite in ascending chunk_index order; moves files to registered/ after processing including on skip."""
        if not chunk_files:
            return self._skip_result(url)

        chunk_files = sorted(chunk_files, key=lambda p: p.stem)
        first_data = self._read_chunk_json(chunk_files[0])
        if first_data is None:
            return IngestUrlResult(
                url=url, n_success=0, n_failed=len(chunk_files), skipped=False
            )

        if not self._validate_artifact(
            first_data, "chunk", strict=self._strict_artifact_validation
        ):
            return self._validation_failure_result(url, chunk_files)

        title = first_data.get("title", "")
        lang = first_data.get("lang", "en")
        etag = first_data.get("etag")
        last_modified = first_data.get("last_modified")
        fetched_at = first_data.get("fetched_at")
        chunking_strategy = first_data.get("chunking_strategy", "text")

        doc_id = self._get_or_create_document(
            doc_mgr,
            db,
            url,
            title,
            lang,
            force,
            etag,
            last_modified,
            chunking_strategy,
            fetched_at,
        )
        if doc_id is None:
            logger.info("already registered, skipping", extra={"url": url})
            self._move_to_registered(chunk_files)
            return self._skip_result(url)

        db.commit()
        inserted, failed, embed_failed = self._ingest_chunk_files(doc_id, chunk_files)
        self._log_ingestion_result(
            doc_id, url, inserted, len(chunk_files), failed, embed_failed
        )
        self._move_to_registered(chunk_files)
        return IngestUrlResult(
            url=url,
            n_success=inserted,
            n_failed=failed,
            skipped=False,
            n_embed_failed=embed_failed,
        )

    # ── Embedding ─────────────────────────────────────────────────────────────

    def _get_embedding(self, text: str) -> list[float] | None:
        """Return embedding vector for text; validates dimension against embedding_dims config.

        Returns None on empty input, network failure, or dimension mismatch.
        Expected dimension is read from common.toml::embedding_dims (default 384).
        """
        if not text or not text.strip():
            return None
        for attempt in range(self._embed_retry):
            try:
                resp = self._client.post(
                    self._embed_url,
                    # E5 passage prefix is mandatory for document-side embedding
                    json={"content": f"passage: {text}"},
                )
                resp.raise_for_status()
                embedding = orjson.loads(resp.content).get("embedding")
                if not isinstance(embedding, list) or not embedding:
                    raise ValueError("missing or empty 'embedding' field in response")
                if len(embedding) != self._expected_dims:
                    raise ValueError(
                        f"embedding dimension mismatch: expected {self._expected_dims},"
                        f" got {len(embedding)}"
                    )
                return embedding
            except (
                httpx.RequestError,
                httpx.HTTPStatusError,
                orjson.JSONDecodeError,
                ValueError,
            ) as e:
                logger.warning(
                    "embedding attempt %s/%s: %s",
                    attempt + 1,
                    self._embed_retry,
                    e,
                )
                if attempt < self._embed_retry - 1:
                    time.sleep(min(2**attempt, 10))
        return None

    # ── Result helpers ────────────────────────────────────────────────────────

    @staticmethod
    def _skip_result(url: str) -> IngestUrlResult:
        """Return a skipped result for a URL."""
        return IngestUrlResult(url=url, n_success=0, n_failed=0, skipped=True)

    @staticmethod
    def _validation_failure_result(
        url: str, chunk_files: list[Path]
    ) -> IngestUrlResult:
        """Return a failure result when artifact validation fails."""
        return IngestUrlResult(
            url=url, n_success=0, n_failed=len(chunk_files), skipped=False
        )

    @staticmethod
    def _log_ingestion_result(
        doc_id: int,
        url: str,
        inserted: int,
        total: int,
        failed: int,
        embed_failed: int,
    ) -> None:
        """Log the chunk ingestion result."""
        src_type = "file" if url.startswith("file://") else "http"
        logger.info(
            "inserted %s/%s chunks (%s failed, %s embed-failed): %s",
            inserted,
            total,
            failed,
            embed_failed,
            url,
            extra={"doc_id": doc_id, "source_type": src_type, "stage_name": "ingester"},
        )

    @staticmethod
    def _normalize_chunk_index(doc_id: int, path_name: str, idx_raw: int | str) -> int:
        """Convert chunk_index to int, falling back to 0 on failure."""
        try:
            return int(idx_raw)
        except (ValueError, TypeError):
            logger.warning(
                "Invalid chunk_index in %s: %s, using 0",
                path_name,
                idx_raw,
                extra={
                    "doc_id": doc_id,
                    "source_type": "file",
                    "stage_name": "ingester",
                },
            )
            return 0

    # ── Document helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _validate_artifact(
        payload: ChunkJsonRaw,
        expected_type: str,
        *,
        strict: bool = False,
    ) -> bool:
        """Validate artifact_type field; lenient for backward compatibility (missing artifact_type is accepted).

        Returns True when validation passes, False when it fails.
        """
        if strict:
            for required in ("schema_version", "artifact_type", "created_by"):
                if required not in payload:
                    return False
        actual = payload.get("artifact_type")
        if actual is not None and actual != expected_type:
            return False
        return True

    @staticmethod
    def _log_ingest_failure(doc_id: int, path: Path, e: Exception) -> None:
        """Log a chunk ingestion failure."""
        chunk_data = _read_chunk_json_raw(path)
        chunk_url = chunk_data.get("url", "") if chunk_data else ""
        logger.error(
            "Failed to ingest %s: %s",
            path,
            e,
            extra={
                "doc_id": doc_id,
                "url": chunk_url,
                "source_type": "file",
                "stage_name": "ingester",
            },
        )

    def _validate_lang(self, lang: str) -> bool:
        """Return True when lang is a valid value."""
        return lang in _VALID_LANGS

    def _get_or_create_document(
        self,
        doc_mgr: DocumentManager,
        db: SQLiteHelper,
        url: str,
        title: str,
        lang: str,
        force: bool,
        etag: str | None = None,
        last_modified: str | None = None,
        chunking_strategy: str = "text",
        fetched_at: str | None = None,
    ) -> int | None:
        """Register a URL in documents and return its doc_id; returns None when already registered and force=False; force=True deletes existing record first."""
        if not self._validate_lang(lang):
            raise ValueError(
                f"unsupported lang value: {lang!r}"
                f" (must be one of {sorted(_VALID_LANGS)})",
            )
        existing_row = db.execute(
            "SELECT doc_id FROM documents WHERE url = ?",
            (url,),
        ).fetchone()
        if existing_row:
            existing_doc_id: int = existing_row[0]
            if doc_mgr.handle_existing_document(
                url,
                existing_doc_id,
                force,
                etag,
                last_modified,
                fetched_at,
                lambda u: u.startswith("file://"),
            ):
                return None
            doc_mgr.delete_existing_document(existing_doc_id)
        cur = self._insert_document(
            db, url, title, lang, etag, last_modified, chunking_strategy, fetched_at
        )
        return cur.lastrowid

    def _insert_document(
        self,
        db: SQLiteHelper,
        url: str,
        title: str,
        lang: str,
        etag: str | None,
        last_modified: str | None,
        chunking_strategy: str,
        fetched_at: str | None,
    ) -> sqlite3.Cursor:
        """Insert a document row and return the cursor."""
        if fetched_at is not None:
            return db.execute(
                "INSERT INTO documents"
                " (url, title, lang, etag, last_modified, chunking_strategy, fetched_at)"
                " VALUES (?, ?, ?, ?, ?, ?, ?)",
                (url, title, lang, etag, last_modified, chunking_strategy, fetched_at),
            )
        return db.execute(
            "INSERT INTO documents"
            " (url, title, lang, etag, last_modified, chunking_strategy)"
            " VALUES (?, ?, ?, ?, ?, ?)",
            (url, title, lang, etag, last_modified, chunking_strategy),
        )

    def _insert_chunk(
        self,
        db: SQLiteHelper,
        doc_id: int,
        idx: int,
        content: str,
        normalized_content: str | None,
        embedding: list[float],
        chunk_type: str = "",
        source_file: str = "",
    ) -> None:
        """Insert a chunk and its embedding vector; chunks_fts synced via trigger using COALESCE(normalized_content, content); embedding stored as float32 BLOB."""
        cur = db.execute(
            "INSERT INTO chunks (doc_id, chunk_index, content, normalized_content, chunk_type, source_file)"
            " VALUES (?, ?, ?, ?, ?, ?)",
            (doc_id, idx, content, normalized_content or None, chunk_type, source_file),
        )
        chunk_id = cur.lastrowid
        db.execute(
            "INSERT INTO chunks_vec (chunk_id, embedding) VALUES (?, ?)",
            (chunk_id, floats_to_blob(embedding)),
        )

    # ── Bulk file processing ──────────────────────────────────────────────────

    def _read_chunk_json(self, path: Path) -> ChunkJsonRaw | None:
        """Read and parse a chunk JSON file as a raw dict; returns None on failure."""
        return _read_chunk_json_raw(path)

    def _embed_and_store(self, doc_id: int, path: Path) -> tuple[bool, bool]:
        """Embed one chunk and insert it using an independent DB connection; each call opens its own connection for safe parallel writes.

        Returns (chunk_ok, embed_ok).
        chunk_ok=False means total failure (parse/DB error or embed failure).
        embed_ok=False specifically means embedding failed (content was valid).
        """
        data = self._read_chunk_json(path)
        if data is None:
            return False, False
        if not self._validate_artifact(
            data, "chunk", strict=self._strict_artifact_validation
        ):
            logger.warning(
                "artifact validation failed for %s",
                path.name,
                extra={"source_type": "file", "stage_name": "ingester"},
            )
            return False, False
        content: str = data.get("content", "")
        nc_raw = data.get("normalized_content")
        normalized_content: str | None = (
            nc_raw if isinstance(nc_raw, str) and nc_raw else None
        )
        idx_raw = data.get("chunk_index", 0)
        idx = self._normalize_chunk_index(doc_id, path.name, idx_raw)
        chunk_type: str = data.get("chunk_type", "") or ""
        source_file: str = data.get("source_file", "") or ""
        # Embed original content; E5 understands raw Japanese.
        # normalized_content is for FTS only and not used for embedding.
        embedding = self._get_embedding(content)
        if embedding is None:
            chunk_url = data.get("url", "")
            logger.warning(
                "embedding failed for %s: %r",
                path.name,
                content[:60],
                extra={
                    "doc_id": doc_id,
                    "url": chunk_url,
                    "source_type": "file",
                    "stage_name": "ingester",
                },
            )
            return False, False
        with SQLiteHelper(
            db_path=self._rag_db_path,
            sqlite_vec_so=self._sqlite_vec_so,
            sqlite_timeout=self._sqlite_timeout,
            sqlite_busy_timeout_ms=self._sqlite_busy_timeout_ms,
        ).open(write_mode=True) as db:
            self._insert_chunk(
                db,
                doc_id,
                idx,
                content,
                normalized_content,
                embedding,
                chunk_type,
                source_file,
            )
            db.commit()
        return True, True

    def _ingest_chunk_files(
        self, doc_id: int, chunk_files: list[Path]
    ) -> tuple[int, int, int]:
        """Embed and insert chunk files in parallel via ThreadPoolExecutor; returns (n_inserted, n_failed, n_embed_failed)."""
        inserted = 0
        failed = 0
        embed_failed = 0
        with ThreadPoolExecutor(max_workers=self._embed_workers) as executor:
            futures = {
                executor.submit(self._embed_and_store, doc_id, path): path
                for path in chunk_files
            }
            for future in as_completed(futures):
                path = futures[future]
                try:
                    chunk_ok, embed_ok = future.result()
                    if chunk_ok:
                        inserted += 1
                    else:
                        failed += 1
                        if not embed_ok:
                            embed_failed += 1
                except (
                    httpx.HTTPStatusError,
                    httpx.RequestError,
                    OSError,
                    ValueError,
                    TypeError,
                ) as e:
                    self._log_ingest_failure(doc_id, path, e)
                    failed += 1
        return inserted, failed, embed_failed

    def _group_chunks_by_url(self, chunk_files: list[Path]) -> dict[str, list[Path]]:
        """Group chunk files by URL read from their JSON 'url' field."""
        url_groups: dict[str, list[Path]] = defaultdict(list)
        for path in chunk_files:
            data = self._read_chunk_json(path)
            if data is None:
                continue
            url: str = data.get("url", "")
            if not url:
                logger.warning(
                    "url field missing: %s",
                    path.name,
                    extra={"source_type": "file", "stage_name": "ingester"},
                )
                continue
            # Accept file:// URLs from local file ingestion in addition to http/https
            if not validate_url(url) and not url.startswith("file://"):
                logger.warning(
                    "invalid url %r in %s, skipping",
                    url,
                    path.name,
                    extra={"source_type": "file", "stage_name": "ingester"},
                )
                continue
            url_groups[url].append(path)
        return url_groups

    def _process_url_groups(
        self,
        doc_mgr: DocumentManager,
        db: SQLiteHelper,
        url_groups: dict[str, list[Path]],
        force: bool,
    ) -> list[IngestUrlResult]:
        """Iterate over URL groups and ingest each; log exceptions without stopping."""
        results: list[IngestUrlResult] = []
        for url, paths in url_groups.items():
            try:
                results.append(self.ingest_url_group(doc_mgr, db, url, paths, force))
            except (OSError, RuntimeError, ValueError, sqlite3.OperationalError):
                logger.exception("ingest_url_group failed: %s", url)
                results.append(
                    IngestUrlResult(url=url, n_success=0, n_failed=-1, skipped=False)
                )
        return results

    def _move_to_registered(self, paths: list[Path]) -> None:
        """Move ingested chunk files to registered/."""
        self._registered_dir.mkdir(parents=True, exist_ok=True)
        for path in paths:
            dest = self._registered_dir / path.name
            try:
                shutil.move(str(path), str(dest))
            except OSError as e:
                chunk_data = self._read_chunk_json(path)
                chunk_url = chunk_data.get("url", "") if chunk_data else ""
                logger.error(
                    "move failed %s → %s: %s",
                    path,
                    dest,
                    e,
                    extra={
                        "url": chunk_url,
                        "source_type": "file",
                        "stage_name": "ingester",
                    },
                )


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Embedding generation and DB ingestion:"
            " rag-src/chunk/*.json → SQLite → rag-src/registered/"
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Force delete and re-ingest already registered URLs",
    )
    args = parser.parse_args()

    ingester = RagIngester()
    ingester.ingest_all(args.force)


if __name__ == "__main__":
    from shared.config_loader import ConfigLoader

    ConfigLoader.restrict_to("ingester.toml")
    main()
