repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        pass_filenames: false
        additional_dependencies:
          - types-requests>=2.32
          - types-beautifulsoup4>=4.12
          - orjson>=3.9
