[tox]
envlist = lint, typecheck, tests
skip_missing_interpreters = true

[testenv]
deps =
    pytest
    pytest-asyncio
    pytest-cov
    pytest-mock
    pytest-randomly
    pytest-rerunfailures
    pytest-subprocess
    pytest-testmon
    pytest-timeout
    pytest-xdist
    coverage
    diff-cover
    ruff
    mypy
    pyright
    bandit
    pre-commit
commands =
    tests: uv run pytest {posargs}
    lint: uv run ruff format --check scripts/
    lint: uv run ruff check scripts/
    typecheck: uv run mypy scripts/
    typecheck: uv run pyright scripts/