"""tests/test_installer_templates.py
Unit tests for mcp/installer_templates.py — Template generators for new MCP HTTP servers.
All functions return strings; no file I/O.
"""

from __future__ import annotations

import pytest
from mcp.installer_templates import (
    generate_agent_toml_mcp_snippet,
    generate_confd_template,
    generate_config_toml,
    generate_config_toml_for_role,
    generate_initd_script,
    generate_server_script,
    tool_definition_snippet,
)

# ── generate_server_script ───────────────────────────────────────────────────


class TestGenerateServerScript:
    def test_returns_python_script(self) -> None:
        result = generate_server_script("testserver", "testmod", 8080)
        assert "#!/usr/bin/env python3" in result
        assert "from fastapi import FastAPI" in result

    def test_contains_server_name_and_module(self) -> None:
        result = generate_server_script("myservice", "myservice_mod", 9000)
        assert "myservice-mcp" in result
        assert "mcp.myservice_mod.server" in result
        assert "myservice_mod_sample_tool" in result

    def test_contains_dispatch_and_class(self) -> None:
        # name_to_class("svc") → "Svc" (PascalCase), so class is SvcMCPServer
        result = generate_server_script("svc", "svcmod", 7000)
        assert "_DISPATCH" in result
        assert "SvcMCPServer" in result
        assert "async def dispatch" in result

    def test_contains_health_and_tools_endpoints(self) -> None:
        result = generate_server_script("x", "xmod", 1234)
        assert '@app.get("/health")' in result
        assert '@app.get("/v1/tools")' in result
        assert '@app.post("/v1/call_tool")' in result


# ── generate_config_toml ─────────────────────────────────────────────────────


class TestGenerateConfigToml:
    def test_returns_toml_with_timeout(self) -> None:
        result = generate_config_toml("svc")
        assert "http_timeout = 30.0" in result
        assert "Generated by" in result


# ── generate_config_toml_for_role ───────────────────────────────────────────


class TestGenerateConfigTomlForRole:
    def test_sqlite_role_has_db_allowlist(self) -> None:
        result = generate_config_toml_for_role("svc", "sqlite")
        assert "db_allowlist" in result
        assert "max_rows = 100" in result
        assert "http_timeout = 30.0" in result

    def test_shell_role_has_command_allowlist(self) -> None:
        result = generate_config_toml_for_role("svc", "shell")
        assert "command_allowlist" in result
        assert "max_output_kb = 4096" in result
        assert "timeout_sec = 60" in result
        assert "env_allowlist" in result

    def test_git_role_has_repo_and_read_only(self) -> None:
        result = generate_config_toml_for_role("svc", "git")
        assert "allowed_repo_paths" in result
        assert "read_only = true" in result
        assert "max_log_entries = 50" in result
        assert "auth_token" in result
        assert "audit_log_path" in result

    def test_ci_role_has_github_and_repo_allowlist(self) -> None:
        result = generate_config_toml_for_role("svc", "ci")
        assert "github_token" in result
        assert "repo_allowlist" in result
        assert "workflow_allowlist" in result
        assert "max_log_size_kb = 256" in result

    def test_unknown_role_raises_value_error(self) -> None:
        with pytest.raises(ValueError, match="Unknown role"):
            generate_config_toml_for_role("svc", "unknown")


# ── generate_agent_toml_mcp_snippet ─────────────────────────────────────────


class TestGenerateAgentTomlMcpSnippet:
    def test_sqlite_role(self) -> None:
        result = generate_agent_toml_mcp_snippet("svc", 8080, "sqlite")
        assert "[mcp_servers.svc]" in result
        assert 'url              = "http://127.0.0.1:8080"' in result
        assert 'role             = "query"' in result
        assert "svc_query_sqlite" in result

    def test_shell_role(self) -> None:
        result = generate_agent_toml_mcp_snippet("svc", 9000, "shell")
        assert 'role             = "execute"' in result
        assert "svc_run" in result

    def test_git_role(self) -> None:
        result = generate_agent_toml_mcp_snippet("svc", 7000, "git")
        assert 'role             = "vcs"' in result
        assert "git_status" in result
        assert "git_push" in result

    def test_ci_role(self) -> None:
        result = generate_agent_toml_mcp_snippet("svc", 6000, "ci")
        assert 'role             = "cicd"' in result
        assert "trigger_workflow" in result
        assert "get_workflow_logs" in result

    def test_unknown_role_raises_value_error(self) -> None:
        with pytest.raises(ValueError, match="Unknown role"):
            generate_agent_toml_mcp_snippet("svc", 5000, "unknown")


# ── generate_initd_script ───────────────────────────────────────────────────


class TestGenerateInitdScript:
    def test_returns_openrc_script(self) -> None:
        result = generate_initd_script("svc", "svcmod", 8080)
        assert "#!/sbin/openrc-run" in result
        assert "uvicorn" in result
        assert "127.0.0.1" in result
        assert "--port 8080" in result

    def test_contains_package_path(self) -> None:
        result = generate_initd_script("svc", "svcmod", 9000)
        assert "mcp.svcmod.server:app" in result

    def test_contains_log_and_pid_paths(self) -> None:
        result = generate_initd_script("myservice", "myservice_mod", 7000)
        assert "/opt/llm/logs/myservice.log" in result
        assert "${RC_SVCNAME}.pid" in result


# ── generate_confd_template ─────────────────────────────────────────────────


class TestGenerateConfdTemplate:
    def test_contains_api_key_placeholder(self) -> None:
        result = generate_confd_template("my-service")
        assert "MY_SERVICE_API_KEY=" in result

    def test_uppercase_conversion(self) -> None:
        result = generate_confd_template("test-server")
        assert "TEST_SERVER_API_KEY=" in result

    def test_contains_restart_instructions(self) -> None:
        result = generate_confd_template("svc")
        assert "rc-service svc restart" in result


# ── tool_definition_snippet ─────────────────────────────────────────────────


class TestToolDefinitionSnippet:
    def test_returns_json_block(self) -> None:
        result = tool_definition_snippet("testmod", "TestServer")
        assert '"type": "function"' in result
        assert '"name": "testmod_sample_tool"' in result

    def test_contains_parameters_schema(self) -> None:
        result = tool_definition_snippet("mymod", "MySrv")
        assert '"parameters"' in result
        assert '"required": ["query"]' in result
        # Description includes "Replace with real description." suffix
        assert "Sample tool for MySrv" in result
