#!/usr/bin/env python3
"""
mcp/installer.py
Template generator for new MCP HTTP servers.
Called from CommandRegistry._cmd_mcp_install() via `/mcp install <name>`.

Generates:
  scripts/mcp/<module>/__init__.py  — empty package marker
  scripts/mcp/<module>/server.py    — skeleton FastAPI server
  config/<module>_mcp_server.toml   — config TOML template
  init.d/<name>                     — OpenRC service script (chmod 755)
  conf.d/<name>                     — API key env template (optional)
"""

import re
import textwrap
from pathlib import Path

# Built-in service ports reserved by the system.
_RESERVED_PORTS: frozenset[int] = frozenset({8001, 8002, 8003, 8004, 8005, 8006})
_PORT_START = 8007

# Repo root: scripts/mcp/ is two levels below the repo root.
_REPO_ROOT = Path(__file__).parent.parent.parent

# Allowed server name pattern: lowercase letters, digits, hyphens; starts with a letter.
_NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")


def validate_server_name(server_name: str) -> str | None:
    """Return None if valid, or an error message string if invalid."""
    if not server_name:
        return "Server name must not be empty."
    if not _NAME_RE.match(server_name):
        return (
            f"Invalid server name {server_name!r}. "
            "Use lowercase letters, digits, and hyphens; must start with a letter."
        )
    return None


def name_to_module(server_name: str) -> str:
    """Convert service name (hyphens allowed) to Python module identifier."""
    return re.sub(r"[^a-z0-9]", "_", server_name.lower())


def name_to_class(server_name: str) -> str:
    """Convert service name to PascalCase class name prefix."""
    return "".join(w.capitalize() for w in re.split(r"[-_]+", server_name))


def scan_used_ports() -> set[int]:
    """Return set of ports found in init.d/ --port arguments plus reserved ones."""
    used: set[int] = set(_RESERVED_PORTS)
    initd_dir = _REPO_ROOT / "init.d"
    if not initd_dir.exists():
        return used
    for f in initd_dir.iterdir():
        if not f.is_file():
            continue
        for m in re.finditer(r"--port\s+(\d+)", f.read_text(errors="ignore")):
            used.add(int(m.group(1)))
    return used


def suggest_port() -> int:
    """Return the lowest available port >= _PORT_START."""
    used = scan_used_ports()
    port = _PORT_START
    while port in used:
        port += 1
    return port


def generate_server_script(server_name: str, module: str, port: int) -> str:
    """Return skeleton FastAPI MCP server script content."""
    cls = name_to_class(server_name) + "MCPServer"
    pkg_path = f"mcp.{module}.server"
    # Double braces {{ }} produce literal { } in the f-string output.
    # The _sample_tool f-string uses {{args}} so the generated code has {args}.
    return textwrap.dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"
        mcp/{module}/server.py
        {server_name} MCP server — generated by `/mcp install`.
        Implement _DISPATCH handlers and update _MCP_TOOLS, then add tool
        definitions to config/agent.toml and register in config/agent.toml.
        \"\"\"

        import logging
        from typing import Any

        from fastapi import FastAPI
        from mcp.server import MCPServer, ToolArgs, dispatch_tool
        from mcp.models import CallToolRequest, CallToolResponse

        logger = logging.getLogger(__name__)

        app = FastAPI(title="{server_name}-mcp")

        # Tool definitions: returned by GET /v1/tools and registered in agent.toml.
        _MCP_TOOLS: list[dict] = [
            {{
                "name": "{module}_sample_tool",
                "description": "Sample tool for {server_name}. Replace with real description.",
            }},
        ]

        # Dispatch table: tool name -> async handler coroutine.
        _DISPATCH: dict[str, Any] = {{}}


        async def _sample_tool(args: ToolArgs) -> str:
            # Replace with real implementation.
            return f"[{server_name}] args={{args}}"


        _DISPATCH["{module}_sample_tool"] = _sample_tool


        class {cls}(MCPServer):
            server_name = "{server_name}"
            server_version = "1.0.0"
            http_port = {port}
            app_module = "{pkg_path}:app"
            mcp_tools = _MCP_TOOLS

            async def dispatch(self, name: str, args: dict) -> tuple[str, bool]:
                return await dispatch_tool(_DISPATCH, name, args)


        @app.get("/health")
        async def health() -> dict:
            return {{"status": "ok"}}


        @app.get("/v1/tools")
        async def list_tools() -> dict:
            return {{"tools": _MCP_TOOLS}}


        @app.post("/v1/call_tool")
        async def call_tool(req: CallToolRequest) -> CallToolResponse:
            result, is_error = await {cls}().dispatch(req.name, req.args)
            return CallToolResponse(result=result, is_error=is_error)


        if __name__ == "__main__":
            {cls}().run()
        """)


def generate_config_toml(server_name: str) -> str:
    """Return TOML content for config/<module>_mcp_server.toml."""
    return textwrap.dedent(f"""\
        # Generated by `/mcp install {server_name}`. Replace with real settings.

        # HTTP request timeout in seconds
        http_timeout = 30.0
        """)


def generate_config_toml_for_role(server_name: str, role: str) -> str:
    """Return role-specific TOML for config/<module>_mcp_server.toml."""
    if role == "sqlite":
        return textwrap.dedent(f"""\
            # Generated by `/mcp install {server_name}` (role: sqlite).

            # HTTP request timeout in seconds
            http_timeout = 30.0

            # Absolute paths of databases that may be queried; empty list = reject all.
            db_allowlist = [
                # "/opt/llm/db/main.db",
            ]

            # Maximum rows returned per query
            max_rows = 100
            """)
    if role == "shell":
        return textwrap.dedent(f"""\
            # Generated by `/mcp install {server_name}` (role: shell).

            # HTTP request timeout in seconds
            http_timeout = 30.0

            # Commands allowed to execute; use full paths or base names.
            # Empty list = reject all commands.
            command_allowlist = [
                # "/bin/bash",
                # "python3",
            ]

            # Maximum combined stdout+stderr in KB
            max_output_kb = 4096

            # Per-invocation timeout in seconds
            timeout_sec = 60

            # Environment variables forwarded to subprocess; empty = block all.
            env_allowlist = [
                # "PATH",
                # "HOME",
            ]
            """)
    if role == "git":
        return textwrap.dedent(f"""\
            # Generated by `/mcp install {server_name}` (role: git).
            # [Security] allowed_repo_paths empty = deny all (fail-closed).
            # Set read_only = false only when write operations (add/commit/push) are required.

            # Absolute paths of git repositories accessible via this server; empty = deny all.
            allowed_repo_paths = [
                # "/opt/llm/myrepo",
            ]

            # When true, only read-only tools (status/log/diff/branch/show) are allowed.
            read_only = true

            # Maximum commit entries returned by git_log
            max_log_entries = 50

            # Bearer token for HTTP auth; empty string = auth disabled.
            auth_token = ""

            # Path for structured audit log (JSON-lines)
            audit_log_path = "/opt/llm/logs/{server_name}.log"
            """)
    if role == "ci":
        return textwrap.dedent(f"""\
            # Generated by `/mcp install {server_name}` (role: ci).
            # [Security] repo_allowlist empty = deny all (fail-closed).
            # workflow_allowlist empty = allow all workflows (fail-open).

            # GitHub Personal Access Token (needs repo + workflow scopes).
            github_token = ""

            # Repositories allowed to trigger/inspect; 'owner/repo' format.
            # Empty list = deny all (fail-closed).
            repo_allowlist = [
                # "myorg/myrepo",
            ]

            # Workflow file names or IDs permitted to trigger; empty = allow all.
            workflow_allowlist = [
                # "ci.yml",
            ]

            # Maximum log size returned by get_workflow_logs, in KB.
            max_log_size_kb = 256

            # Bearer token for HTTP auth; empty string = auth disabled.
            auth_token = ""
            """)
    return generate_config_toml(server_name)


def generate_agent_toml_mcp_snippet(server_name: str, port: int, role: str) -> str:
    """Return a [mcp_servers.<name>] snippet for config/agent.toml."""
    module = name_to_module(server_name)
    if role == "sqlite":
        role_val = "query"
        tool_names = f'["{module}_query_sqlite"]  # update to match actual tool name'
    elif role == "shell":
        role_val = "execute"
        tool_names = f'["{module}_run"]  # update to match actual tool name'
    elif role == "git":
        role_val = "vcs"
        tool_names = (
            '["git_status", "git_log", "git_diff", "git_branch", "git_show",'
            ' "git_add", "git_commit", "git_checkout", "git_pull", "git_push"]'
        )
    elif role == "ci":
        role_val = "cicd"
        tool_names = (
            '["trigger_workflow", "get_workflow_runs",'
            ' "get_workflow_status", "get_workflow_logs"]'
        )
    else:
        role_val = ""
        tool_names = "[]"
    return textwrap.dedent(f"""\
        [mcp_servers.{server_name}]
        transport        = "http"
        url              = "http://127.0.0.1:{port}"
        cmd              = []
        openrc_service   = "{server_name}"
        startup_mode     = "persistent"
        healthcheck_mode = "http"
        auth_token       = ""
        role             = "{role_val}"
        tool_names       = {tool_names}
        """)


def generate_initd_script(server_name: str, module: str, port: int) -> str:
    """Return OpenRC script content for init.d/<server_name>."""
    pkg_app = f"mcp.{module}.server:app"
    return textwrap.dedent(f"""\
        #!/sbin/openrc-run
        # {server_name}: MCP server (FastAPI/Uvicorn :{port}) — generated by `/mcp install`

        description="{server_name} MCP Server (FastAPI/Uvicorn :{port})"

        command="/opt/llm/venv/bin/uvicorn"
        command_args="{pkg_app} --host 127.0.0.1 --port {port} --workers 1"
        command_background="yes"
        command_user="root"

        directory="/opt/llm/scripts"

        pidfile="/run/${{RC_SVCNAME}}.pid"
        output_log="/opt/llm/logs/{server_name}.log"
        error_log="/opt/llm/logs/{server_name}.log"

        depend() {{
            need net
        }}

        start_pre() {{
            checkpath --directory --owner root:root --mode 0755 /opt/llm/logs
        }}
        """)


def generate_confd_template(server_name: str) -> str:
    """Return content for conf.d/<server_name> API key template."""
    upper = server_name.upper().replace("-", "_")
    return textwrap.dedent(f"""\
        # /etc/conf.d/{server_name}
        # {server_name} service environment variables.
        # Generated by `/mcp install {server_name}`.
        #
        # Set required API keys below, then restart the service:
        #   rc-service {server_name} restart

        {upper}_API_KEY=""
        """)


def tool_definition_snippet(module: str, server_name: str) -> str:
    """Return a JSON block suitable for pasting into agent.toml tool_definitions."""
    return textwrap.dedent(f"""\
        {{
          "type": "function",
          "function": {{
            "name": "{module}_sample_tool",
            "description": "Sample tool for {server_name}. Replace with real description.",
            "parameters": {{
              "type": "object",
              "properties": {{
                "query": {{
                  "type": "string",
                  "description": "Input query"
                }}
              }},
              "required": ["query"]
            }}
          }}
        }}""")


def install_mcp_server(
    server_name: str,
    port: int,
    *,
    with_confd: bool = False,
    role: str = "",
    repo_root: Path | None = None,
) -> list[str]:
    """Write template files to the repository tree.

    Returns a list of created file paths.
    Raises FileExistsError if any target file already exists.
    Raises ValueError if server_name fails validation.
    """
    err = validate_server_name(server_name)
    if err:
        raise ValueError(err)

    root = repo_root if repo_root is not None else _REPO_ROOT
    module = name_to_module(server_name)

    targets: dict[Path, str] = {
        root / "scripts" / "mcp" / module / "__init__.py": "",
        root / "scripts" / "mcp" / module / "server.py": generate_server_script(
            server_name, module, port
        ),
        root / "config" / f"{module}_mcp_server.toml": generate_config_toml_for_role(
            server_name, role
        ),
        root / "init.d" / server_name: generate_initd_script(server_name, module, port),
    }
    if with_confd:
        targets[root / "conf.d" / server_name] = generate_confd_template(server_name)

    existing = [str(p) for p in targets if p.exists()]
    if existing:
        raise FileExistsError(f"File(s) already exist: {', '.join(existing)}")

    created: list[str] = []
    for path, content in targets.items():
        path.write_text(content, encoding="utf-8")
        if path.parent.name == "init.d":
            path.chmod(0o755)
        elif path.name == "__init__.py":
            pass  # empty package marker; no chmod needed
        created.append(str(path))
    return created
