#!/usr/bin/env python3
"""
mcp/installer.py
Template generator for new MCP HTTP servers.
Called from CommandRegistry._cmd_mcp_install() via `/mcp install <name>`.

Generates:
  scripts/mcp/<module>/__init__.py  — empty package marker
  scripts/mcp/<module>/server.py    — skeleton FastAPI server
  config/<module>_mcp_server.json   — config JSON template
  init.d/<name>                     — OpenRC service script (chmod 755)
  conf.d/<name>                     — API key env template (optional)
"""

import re
import textwrap
from pathlib import Path

# Built-in service ports reserved by the system.
_RESERVED_PORTS: frozenset[int] = frozenset({8001, 8002, 8003, 8004, 8005, 8006})
_PORT_START = 8007

# Repo root: scripts/mcp/ is two levels below the repo root.
_REPO_ROOT = Path(__file__).parent.parent.parent

# Allowed server name pattern: lowercase letters, digits, hyphens; starts with a letter.
_NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")


def validate_server_name(server_name: str) -> str | None:
    """Return None if valid, or an error message string if invalid."""
    if not server_name:
        return "Server name must not be empty."
    if not _NAME_RE.match(server_name):
        return (
            f"Invalid server name {server_name!r}. "
            "Use lowercase letters, digits, and hyphens; must start with a letter."
        )
    return None


def name_to_module(server_name: str) -> str:
    """Convert service name (hyphens allowed) to Python module identifier."""
    return re.sub(r"[^a-z0-9]", "_", server_name.lower())


def name_to_class(server_name: str) -> str:
    """Convert service name to PascalCase class name prefix."""
    return "".join(w.capitalize() for w in re.split(r"[-_]+", server_name))


def scan_used_ports() -> set[int]:
    """Return set of ports found in init.d/ --port arguments plus reserved ones."""
    used: set[int] = set(_RESERVED_PORTS)
    initd_dir = _REPO_ROOT / "init.d"
    if not initd_dir.exists():
        return used
    for f in initd_dir.iterdir():
        if not f.is_file():
            continue
        for m in re.finditer(r"--port\s+(\d+)", f.read_text(errors="ignore")):
            used.add(int(m.group(1)))
    return used


def suggest_port() -> int:
    """Return the lowest available port >= _PORT_START."""
    used = scan_used_ports()
    port = _PORT_START
    while port in used:
        port += 1
    return port


def generate_server_script(server_name: str, module: str, port: int) -> str:
    """Return skeleton FastAPI MCP server script content."""
    cls = name_to_class(server_name) + "MCPServer"
    pkg_path = f"mcp.{module}.server"
    # Double braces {{ }} produce literal { } in the f-string output.
    # The _sample_tool f-string uses {{args}} so the generated code has {args}.
    return textwrap.dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"
        mcp/{module}/server.py
        {server_name} MCP server — generated by `/mcp install`.
        Implement _DISPATCH handlers and update _MCP_TOOLS, then add tool
        definitions to config/agent.toml and register in config/agent.toml.
        \"\"\"

        import logging
        from typing import Any

        from fastapi import FastAPI
        from mcp.server import MCPServer, ToolArgs, dispatch_tool
        from mcp.models import CallToolRequest, CallToolResponse

        logger = logging.getLogger(__name__)

        app = FastAPI(title="{server_name}-mcp")

        # Tool definitions: returned by GET /v1/tools and registered in agent.toml.
        _MCP_TOOLS: list[dict] = [
            {{
                "name": "{module}_sample_tool",
                "description": "Sample tool for {server_name}. Replace with real description.",
            }},
        ]

        # Dispatch table: tool name -> async handler coroutine.
        _DISPATCH: dict[str, Any] = {{}}


        async def _sample_tool(args: ToolArgs) -> str:
            # Replace with real implementation.
            return f"[{server_name}] args={{args}}"


        _DISPATCH["{module}_sample_tool"] = _sample_tool


        class {cls}(MCPServer):
            server_name = "{server_name}"
            server_version = "1.0.0"
            http_port = {port}
            app_module = "{pkg_path}:app"
            mcp_tools = _MCP_TOOLS

            async def dispatch(self, name: str, args: dict) -> tuple[str, bool]:
                return await dispatch_tool(_DISPATCH, name, args)


        @app.get("/health")
        async def health() -> dict:
            return {{"status": "ok"}}


        @app.get("/v1/tools")
        async def list_tools() -> dict:
            return {{"tools": _MCP_TOOLS}}


        @app.post("/v1/call_tool")
        async def call_tool(req: CallToolRequest) -> CallToolResponse:
            result, is_error = await {cls}().dispatch(req.name, req.args)
            return CallToolResponse(result=result, is_error=is_error)


        if __name__ == "__main__":
            {cls}().run()
        """)


def generate_config_json(server_name: str) -> str:
    """Return JSON content for config/<module>_mcp_server.json."""
    return textwrap.dedent(f"""\
        {{
          "_doc": {{
            "_note": "Generated by `/mcp install {server_name}`. Replace with real settings.",
            "http_timeout": "HTTP request timeout in seconds"
          }},
          "http_timeout": 30.0
        }}
        """)


def generate_initd_script(server_name: str, module: str, port: int) -> str:
    """Return OpenRC script content for init.d/<server_name>."""
    pkg_app = f"mcp.{module}.server:app"
    return textwrap.dedent(f"""\
        #!/sbin/openrc-run
        # {server_name}: MCP server (FastAPI/Uvicorn :{port}) — generated by `/mcp install`

        description="{server_name} MCP Server (FastAPI/Uvicorn :{port})"

        command="/opt/llm/venv/bin/uvicorn"
        command_args="{pkg_app} --host 127.0.0.1 --port {port} --workers 1"
        command_background="yes"
        command_user="root"

        directory="/opt/llm/scripts"

        pidfile="/run/${{RC_SVCNAME}}.pid"
        output_log="/opt/llm/logs/{server_name}.log"
        error_log="/opt/llm/logs/{server_name}.log"

        depend() {{
            need net
        }}

        start_pre() {{
            checkpath --directory --owner root:root --mode 0755 /opt/llm/logs
        }}
        """)


def generate_confd_template(server_name: str) -> str:
    """Return content for conf.d/<server_name> API key template."""
    upper = server_name.upper().replace("-", "_")
    return textwrap.dedent(f"""\
        # /etc/conf.d/{server_name}
        # {server_name} service environment variables.
        # Generated by `/mcp install {server_name}`.
        #
        # Set required API keys below, then restart the service:
        #   rc-service {server_name} restart

        {upper}_API_KEY=""
        """)


def tool_definition_snippet(module: str, server_name: str) -> str:
    """Return a JSON block suitable for pasting into agent.json tool_definitions."""
    return textwrap.dedent(f"""\
        {{
          "type": "function",
          "function": {{
            "name": "{module}_sample_tool",
            "description": "Sample tool for {server_name}. Replace with real description.",
            "parameters": {{
              "type": "object",
              "properties": {{
                "query": {{
                  "type": "string",
                  "description": "Input query"
                }}
              }},
              "required": ["query"]
            }}
          }}
        }}""")


def install_mcp_server(
    server_name: str,
    port: int,
    *,
    with_confd: bool = False,
    repo_root: Path | None = None,
) -> list[str]:
    """Write template files to the repository tree.

    Returns a list of created file paths.
    Raises FileExistsError if any target file already exists.
    Raises ValueError if server_name fails validation.
    """
    err = validate_server_name(server_name)
    if err:
        raise ValueError(err)

    root = repo_root if repo_root is not None else _REPO_ROOT
    module = name_to_module(server_name)

    targets: dict[Path, str] = {
        root / "scripts" / "mcp" / module / "__init__.py": "",
        root / "scripts" / "mcp" / module / "server.py": generate_server_script(
            server_name, module, port
        ),
        root / "config" / f"{module}_mcp_server.json": generate_config_json(
            server_name
        ),
        root / "init.d" / server_name: generate_initd_script(server_name, module, port),
    }
    if with_confd:
        targets[root / "conf.d" / server_name] = generate_confd_template(server_name)

    existing = [str(p) for p in targets if p.exists()]
    if existing:
        raise FileExistsError(f"File(s) already exist: {', '.join(existing)}")

    created: list[str] = []
    for path, content in targets.items():
        path.write_text(content, encoding="utf-8")
        if path.parent.name == "init.d":
            path.chmod(0o755)
        elif path.name == "__init__.py":
            pass  # empty package marker; no chmod needed
        created.append(str(path))
    return created
