"""mcp/installer_templates.py
Template generators for new MCP HTTP servers.
Each function returns a string — no file I/O.
"""

from __future__ import annotations

import textwrap

from mcp.installer_validation import name_to_class, name_to_module


def generate_server_script(server_name: str, module: str, port: int) -> str:
    """Return skeleton FastAPI MCP server script content."""
    cls = name_to_class(server_name) + "MCPServer"
    pkg_path = f"mcp.{module}.server"
    # Double braces {{ }} produce literal { } in the f-string output.
    return textwrap.dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"
        mcp/{module}/server.py
        {server_name} MCP server — generated by `/mcp install`.
        Implement _DISPATCH handlers and update _MCP_TOOLS, then add tool
        definitions to config/agent.toml and register in config/agent.toml.
        \"\"\"

        import logging
        from typing import Any

        from fastapi import FastAPI
        from mcp.server import MCPServer, ToolArgs
        from mcp.dispatch import DispatchResult, dispatch_tool
        from mcp.models import CallToolRequest, CallToolResponse

        logger = logging.getLogger(__name__)

        app = FastAPI(title="{server_name}-mcp")

        # Tool definitions: returned by GET /v1/tools and registered in agent.toml.
        _MCP_TOOLS: list[dict] = [
            {{
                "name": "{module}_sample_tool",
                "description": "Sample tool for {server_name}. Replace with real description.",
            }},
        ]

        # Server key used for live discovery-based routing.
        _SERVER_KEY = "{{server_key}}"  # fmt: skip

        # Dispatch table: tool name -> async handler coroutine.
        _DISPATCH: dict[str, Any] = {{}}


        async def _sample_tool(args: ToolArgs) -> str:
            # Replace with real implementation.
            return f"[{server_name}] args={{args}}"


        _DISPATCH["{module}_sample_tool"] = _sample_tool


        class {cls}(MCPServer):
            server_name = "{server_name}"
            server_version = "1.0.0"
            http_port = {port}
            app_module = "{pkg_path}:app"
            mcp_tools = _MCP_TOOLS

            async def dispatch(self, name: str, args: dict) -> DispatchResult:
                return await dispatch_tool(_DISPATCH, name, args)


        @app.get("/health")
        async def health() -> dict:
            return {{"status": "ok", "ready": True, "dependencies": {{}}, "details": {{}}}}


        @app.get("/v1/tools")
        async def list_tools() -> dict:
            tools_with_keys = [{{**t, "server_key": _SERVER_KEY}} for t in _MCP_TOOLS]
            return {{"tools": tools_with_keys}}


        @app.post("/v1/call_tool")
        async def call_tool(req: CallToolRequest) -> CallToolResponse:
            r = await {cls}().dispatch(req.name, req.args)
            return CallToolResponse(result=r.output, is_error=r.is_error)


        if __name__ == "__main__":
            {cls}().run_http()
        """)


def generate_config_toml(server_name: str) -> str:
    """Return TOML content for config/<module>_mcp_server.toml."""
    return textwrap.dedent(f"""\
        # Generated by `/mcp install {server_name}`. Replace with real settings.

        # HTTP request timeout in seconds
        http_timeout = 30.0
        """)


_VALID_ROLES: frozenset[str] = frozenset({"sqlite", "shell", "git", "ci"})

_ROLE_TPL_SQLITE = textwrap.dedent("""\
    # Generated by `/mcp install {server_name}` (role: sqlite).

    # HTTP request timeout in seconds
    http_timeout = 30.0

    # Absolute paths of databases that may be queried; empty list = reject all.
    db_allowlist = [
        # "/opt/llm/db/main.db",
    ]

    # Maximum rows returned per query
    max_rows = 100
    """)

_ROLE_TPL_SHELL = textwrap.dedent("""\
    # Generated by `/mcp install {server_name}` (role: shell).

    # HTTP request timeout in seconds
    http_timeout = 30.0

    # Commands allowed to execute; use full paths or base names.
    # Empty list = reject all commands.
    command_allowlist = [
        # "/bin/bash",
        # "python3",
    ]

    # Maximum combined stdout+stderr in KB
    max_output_kb = 4096

    # Per-invocation timeout in seconds
    timeout_sec = 60

    # Environment variables forwarded to subprocess; empty = block all.
    env_allowlist = [
        # "PATH",
        # "HOME",
    ]
    """)

_ROLE_TPL_GIT = textwrap.dedent("""\
    # Generated by `/mcp install {server_name}` (role: git).
    # [Security] allowed_repo_paths empty = deny all (fail-closed).
    # Set read_only = false only when write operations (add/commit/push) are required.

    # Absolute paths of git repositories accessible via this server; empty = deny all.
    allowed_repo_paths = [
        # "/opt/llm/myrepo",
    ]

    # When true, only read-only tools (status/log/diff/branch/show) are allowed.
    read_only = true

    # Maximum commit entries returned by git_log
    max_log_entries = 50

    # Bearer token for HTTP auth; empty string = auth disabled.
    auth_token = ""

    # Path for structured audit log (JSON-lines)
    audit_log_path = "/opt/llm/logs/{server_name}.log"
    """)

_ROLE_TPL_CI = textwrap.dedent("""\
    # Generated by `/mcp install {server_name}` (role: ci).
    # [Security] repo_allowlist empty = deny all (fail-closed).
    # workflow_allowlist empty = allow all workflows (fail-open).

    # GitHub Personal Access Token (needs repo + workflow scopes).
    github_token = ""

    # Repositories allowed to trigger/inspect; 'owner/repo' format.
    # Empty list = deny all (fail-closed).
    repo_allowlist = [
        # "myorg/myrepo",
    ]

    # Workflow file names or IDs permitted to trigger; empty = allow all.
    workflow_allowlist = [
        # "ci.yml",
    ]

    # Maximum log size returned by get_workflow_logs, in KB.
    max_log_size_kb = 256

    # Bearer token for HTTP auth; empty string = auth disabled.
    auth_token = ""
    """)

_ROLE_TEMPLATES: dict[str, str] = {
    "sqlite": _ROLE_TPL_SQLITE,
    "shell": _ROLE_TPL_SHELL,
    "git": _ROLE_TPL_GIT,
    "ci": _ROLE_TPL_CI,
}


def _validate_role(role: str) -> None:
    """Raise ValueError when role is not recognized."""
    if role not in _VALID_ROLES:
        raise ValueError(
            f"Unknown role {role!r}. Must be one of {sorted(_VALID_ROLES)}"
        )


def generate_config_toml_for_role(server_name: str, role: str) -> str:
    """Return role-specific TOML for config/<module>_mcp_server.toml.

    Raises ValueError for unknown roles.
    """
    _validate_role(role)
    template = _ROLE_TEMPLATES[role]
    return textwrap.dedent(template).format(server_name=server_name)


_ROLE_ROLE_MAP: dict[str, tuple[str, str]] = {
    "sqlite": (
        "query",
        '["{module}_query_sqlite"]  # update to match actual tool name',
    ),
    "shell": ("execute", '["{module}_run"]  # update to match actual tool name'),
    "git": (
        "vcs",
        '["git_status", "git_log", "git_diff", "git_branch", "git_show",'
        ' "git_add", "git_commit", "git_checkout", "git_pull", "git_push"]',
    ),
    "ci": (
        "cicd",
        '["trigger_workflow", "get_workflow_runs",'
        ' "get_workflow_status", "get_workflow_logs"]',
    ),
}


def generate_agent_toml_mcp_snippet(server_name: str, port: int, role: str) -> str:
    """Return a [mcp_servers.<name>] snippet for config/agent.toml."""
    _validate_role(role)
    module = name_to_module(server_name)
    role_val, tool_names_tpl = _ROLE_ROLE_MAP[role]
    tool_names = tool_names_tpl.format(module=module)
    return textwrap.dedent(f"""\
        [mcp_servers.{server_name}]
        transport        = "http"
        url              = "http://127.0.0.1:{port}"
        cmd              = []
        openrc_service   = "{server_name}"
        startup_mode     = "persistent"
        healthcheck_mode = "http"
        auth_token       = ""
        role             = "{role_val}"
        tool_names       = {tool_names}
        """)


def generate_initd_script(server_name: str, module: str, port: int) -> str:
    """Return OpenRC script content for init.d/<server_name>."""
    pkg_app = f"mcp.{module}.server:app"
    return textwrap.dedent(f"""\
        #!/sbin/openrc-run
        # {server_name}: MCP server (FastAPI/Uvicorn :{port}) — generated by `/mcp install`

        description="{server_name} MCP Server (FastAPI/Uvicorn :{port})"

        command="/opt/llm/venv/bin/uvicorn"
        command_args="{pkg_app} --host 127.0.0.1 --port {port} --workers 1"
        command_background="yes"
        command_user="root"

        directory="/opt/llm/scripts"

        pidfile="/run/${{RC_SVCNAME}}.pid"
        output_log="/opt/llm/logs/{server_name}.log"
        error_log="/opt/llm/logs/{server_name}.log"

        depend() {{
            need net
        }}

        start_pre() {{
            checkpath --directory --owner root:root --mode 0755 /opt/llm/logs
        }}
        """)


def generate_confd_template(server_name: str) -> str:
    """Return content for conf.d/<server_name> API key template."""
    upper = server_name.upper().replace("-", "_")
    return textwrap.dedent(f"""\
        # /etc/conf.d/{server_name}
        # {server_name} service environment variables.
        # Generated by `/mcp install {server_name}`.
        #
        # Set required API keys below, then restart the service:
        #   rc-service {server_name} restart

        {upper}_API_KEY=""
        """)


def tool_definition_snippet(module: str, server_name: str) -> str:
    """Return a JSON block suitable for pasting into agent.toml tool_definitions."""
    return textwrap.dedent(f"""\
        {{
          "type": "function",
          "function": {{
            "name": "{module}_sample_tool",
            "description": "Sample tool for {server_name}. Replace with real description.",
            "parameters": {{
              "type": "object",
              "properties": {{
                "query": {{
                  "type": "string",
                  "description": "Input query"
                }}
              }},
              "required": ["query"]
            }}
          }}
        }}""")
