from __future__ import annotations

import hashlib
import logging
import os
import socket
from pathlib import Path

logger = logging.getLogger(__name__)


def _make_consumer_id(consumer_name: str) -> str:
    """Generate a collision-resistant consumer ID from name+host+pid.

    Deprecated: This function is provided for testing purposes only and consumers
    should supply their own stable consumer_ids. Consumer IDs are always client-supplied
    via the `consumer_id` query parameter — never auto-generated by the server.
    """
    stable_key = f"{consumer_name}:{socket.gethostname()}:{os.getpid()}"
    return hashlib.sha256(stable_key.encode()).hexdigest()[:16]


def read_offset(offsets_dir: str, consumer_id: str) -> int:
    safe_id = _sanitize_consumer_id(consumer_id)
    path = Path(offsets_dir) / safe_id
    try:
        return int(path.read_text().strip())
    except (FileNotFoundError, ValueError):
        return 0


def write_offset(offsets_dir: str, consumer_id: str, seq: int) -> None:
    safe_id = _sanitize_consumer_id(consumer_id)
    dir_path = Path(offsets_dir)
    dir_path.mkdir(parents=True, exist_ok=True)
    path = dir_path / safe_id
    path.write_text(str(seq))
    logger.debug("offset written consumer=%s seq=%d", consumer_id, seq)


def _sanitize_consumer_id(consumer_id: str) -> str:
    """Sanitize consumer_id for use as an offset filename.

    Replaces path traversal characters (., /, ..) with underscores to prevent
    directory traversal attacks via the consumer_id parameter.
    Returns 'default' if the sanitized result is empty.
    """
    safe_id = consumer_id.replace("..", "_").replace(".", "_").replace("/", "_")
    return safe_id if safe_id else "default"
