#!/usr/bin/env python3
"""
ChunkSplitter.py
Reads rag-src/*.txt (JSON files generated by Crawler.py), splits text and code
into chunks, and saves them to rag-src/chunk/{stem}-{idx:04d}.txt.

Output file format: JSON
  {url, title, lang, source_file, chunk_index, chunk_type, content}
  chunk_type: "text" or "code"

Pipeline position: Crawler.py → ChunkSplitter.py → RagIngester.py
"""

import argparse
import re
from pathlib import Path
from typing import Any

import orjson
from chunk_english import ChunkEnglishMixin
from chunk_japanese import ChunkJapaneseMixin
from chunk_utils import merge_text_items
from config_loader import ConfigLoader
from logger import Logger
from pipeline_utils import collect_source_files, is_already_processed, read_json_file
from sudachipy import dictionary as sudachi_dict
from sudachipy import tokenizer as sudachi_tok

logger = Logger(__name__, "/opt/llm/logs/chunk.log")


# ──────────────────────────────────────────────────────────────────────────────
# ChunkSplitter class
# ──────────────────────────────────────────────────────────────────────────────
class ChunkSplitter(ChunkEnglishMixin, ChunkJapaneseMixin):
    """
    Splits crawl output (JSON files in rag-src/) into text and code chunks
    and writes them to rag-src/chunk/ for ingestion by RagIngester.
    """

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        cfg: dict[str, Any] = config or ConfigLoader().load("rag_pipeline.json")
        rag_src_dir = Path(cfg["rag_src_dir"])
        self._chunk_dir: Path = rag_src_dir / "chunk"
        self._min_chunk: int = int(cfg["min_chunk"])
        self._max_chunk: int = int(cfg["max_chunk"])
        self._en_stopwords: frozenset[str] = frozenset(cfg["en_stopwords"])
        self._ja_stop_pos: frozenset[str] = frozenset(cfg["ja_stop_pos"])
        self._chunk_overlap: int = int(cfg.get("chunk_overlap", 50))
        # Markdown heading-based snippet mode: split on # / ## / ### boundaries
        self._md_index_enable: bool = bool(cfg.get("md_index_enable", False))
        self._md_snippet_max_chars: int = int(cfg.get("md_snippet_max_chars", 600))
        self._rag_src_dir: Path = rag_src_dir
        # SplitMode.C: longest compound unit; optimal for NLP downstream tasks
        sd_dict = sudachi_dict.Dictionary(dict="core")
        self._sd_tkn = sd_dict.create()
        self._split_c = sudachi_tok.Tokenizer.SplitMode.C

    # ── Public interface ──────────────────────────────────────────────────────

    def process_all(self, target: Path | None = None, force: bool = False) -> int:
        """
        Process all *.txt files in rag-src/ (or a single file when target is given).
        Returns total chunks written.
        """
        paths = self._collect_targets(target)
        if not paths:
            logger.info("No source files to process")
            return 0
        total = 0
        for path in paths:
            try:
                total += self.process_file(path, force)
            except Exception:
                logger.exception(f"process_file failed: {path}")
        logger.info(f"=== done: {total} chunks from {len(paths)} files ===")
        return total

    def process_file(self, src_path: Path, force: bool = False) -> int:
        """
        Read a JSON file generated by Crawler, split it into chunks, and write output.
        Returns the number of chunks written.

        Idempotency: when force=False, skip if {stem}-0000.txt already exists.
        """
        if not src_path.exists():
            logger.error(f"Source file does not exist: {src_path}")
            return 0
        sentinel = self._chunk_dir / f"{src_path.stem}-0000.txt"
        if is_already_processed(sentinel, force):
            logger.info(f"skip (already chunked): {src_path.name}")
            return 0
        data = self._read_source_data(src_path)
        if data is None:
            return 0
        chunks = self._build_chunk_list(data)
        written = self._write_chunk_files(chunks, data, src_path)
        logger.info(f"chunked {written} chunks from {src_path.name}")
        return written

    # ── English and Japanese chunking ─────────────────────────────────────────
    # Provided by ChunkEnglishMixin and ChunkJapaneseMixin respectively.
    # ─────────────────────────────────────────────────────────────────────────

    # ── Markdown heading chunking ──────────────────────────────────────────────

    def _is_markdown_source(self, data: dict[str, Any]) -> bool:
        """Return True when the source should use heading-based snippet chunking.

        Triggered by .md/.markdown URL extension or inline heading detection
        when md_index_enable is set.
        """
        if not self._md_index_enable:
            return False
        url = data.get("url", "")
        if url.endswith((".md", ".markdown", ".mdx")):
            return True
        content = data.get("content", "")
        # Treat as Markdown when at least two heading lines are found
        return len(re.findall(r"^#{1,6} .+", content, re.MULTILINE)) >= 2

    def _chunk_markdown_by_heading(self, text: str) -> list[str]:
        """Split Markdown text at heading boundaries into snippet chunks.

        Each heading and its following content up to the next heading is one
        snippet.  Sections exceeding md_snippet_max_chars are further split
        using _chunk_english() as a fallback.
        """
        # Split before each heading line; keep the heading with its section
        sections = re.split(r"(?=^#{1,6} )", text.strip(), flags=re.MULTILINE)
        chunks: list[str] = []
        for section in sections:
            section = section.strip()
            if not section:
                continue
            if len(section) <= self._md_snippet_max_chars:
                if len(section) >= self._min_chunk:
                    chunks.append(section)
            else:
                # Section too large; fall back to sentence-level chunking
                chunks.extend(self._chunk_english(section))
        return chunks

    # ── Code chunking ─────────────────────────────────────────────────────────

    def _chunk_code(self, code: str) -> list[str]:
        """Split a code block at blank lines (function/class boundaries).

        Code is not subject to stopword removal or morphological analysis.
        """
        blocks = re.split(r"\n{2,}", code.strip())
        return merge_text_items(
            blocks, "\n\n", self._min_chunk, self._max_chunk, self._chunk_overlap
        )

    # ── File I/O ──────────────────────────────────────────────────────────────

    def _read_source_data(self, src_path: Path) -> dict[str, Any] | None:
        """Read and parse a JSON crawl file. Delegates to pipeline_utils."""
        return read_json_file(src_path)

    def _build_chunk_list(self, data: dict[str, Any]) -> list[tuple[str, str, str]]:
        """
        Extract content from a crawl record and split into
        (chunk_type, content, normalized_content) triples.
        normalized_content is populated only for Japanese text chunks;
        empty string for English text and code (FTS5 falls back to content via
        COALESCE in the trigger).
        """
        lang: str = data.get("lang", "en")
        content: str = data.get("content", "")
        code_blocks: list[str] = data.get("code_blocks", [])

        # Build text triples; guard on empty content to skip chunking entirely
        text_triples: list[tuple[str, str, str]] = []
        if content:
            use_markdown: bool = self._is_markdown_source(data)
            if use_markdown:
                text_triples = [
                    ("text", c, "") for c in self._chunk_markdown_by_heading(content)
                ]
            elif lang == "ja":
                text_triples = [
                    ("text", orig, norm) for orig, norm in self._chunk_japanese(content)
                ]
            else:
                text_triples = [("text", c, "") for c in self._chunk_english(content)]

        # Build code triples from each code block independently
        code_triples: list[tuple[str, str, str]] = []
        for cb in code_blocks:
            code_triples.extend([("code", c, "") for c in self._chunk_code(cb)])

        return text_triples + code_triples

    def _write_chunk_files(
        self,
        chunks: list[tuple[str, str, str]],
        data: dict[str, Any],
        src_path: Path,
    ) -> int:
        """Write (chunk_type, content, normalized_content) triples to chunk_dir."""
        # Guard: nothing to write
        if not chunks:
            return 0
        self._chunk_dir.mkdir(parents=True, exist_ok=True)
        # Extract document-level metadata shared across all chunk files
        url: str = data.get("url", "")
        title: str = data.get("title", "")
        lang: str = data.get("lang", "en")
        etag: str | None = data.get("etag")
        last_modified: str | None = data.get("last_modified")
        written: int = 0
        for idx, (chunk_type, chunk_content, norm_content) in enumerate(chunks):
            out_path = self._chunk_dir / f"{src_path.stem}-{idx:04d}.txt"
            payload: dict[str, Any] = {
                "url": url,
                "title": title,
                "lang": lang,
                "source_file": src_path.name,
                "chunk_index": idx,
                "chunk_type": chunk_type,
                "content": chunk_content,
                "normalized_content": norm_content or None,
                "etag": etag,
                "last_modified": last_modified,
            }
            try:
                out_path.write_bytes(
                    orjson.dumps(payload, option=orjson.OPT_INDENT_2),
                )
                written += 1
            except OSError as e:
                logger.error(f"failed to write chunk {out_path}: {e}")
        return written

    def _collect_targets(self, target: Path | None) -> list[Path]:
        """Return source files to process. Delegates to pipeline_utils."""
        return collect_source_files(self._rag_src_dir, target)


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(
        description="Chunking: rag-src/*.txt → rag-src/chunk/{stem}-{idx:04d}.txt"
    )
    parser.add_argument(
        "--file",
        help="Process a single file (default: process all files in rag-src/*.txt)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-process even if output chunks already exist",
    )
    args = parser.parse_args()

    target: Path | None = None
    if args.file:
        target = Path(args.file)
        if not target.exists():
            parser.error(f"File does not exist: {target}")

    splitter = ChunkSplitter()
    splitter.process_all(target, args.force)


if __name__ == "__main__":
    main()
