#!/usr/bin/env python3
"""
RagIngester.py
Reads rag-src/chunk/*.txt (JSON files generated by ChunkSplitter.py),
generates embeddings, and ingests them into SQLite (documents / chunks / chunks_vec).
Processed files are moved to rag-src/registered/.

Pipeline position: Crawler.py → ChunkSplitter.py → RagIngester.py
"""

import argparse
import shutil
import time
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

import httpx
import orjson
from config_loader import ConfigLoader
from logger import Logger
from pipeline_utils import read_json_file
from rag_utils import floats_to_blob, validate_url
from sqlite_helper import SQLiteHelper

logger = Logger(__name__, "/opt/llm/logs/ingest.log")

# Accepted lang values enforced by the documents.lang CHECK constraint
_VALID_LANGS: frozenset[str] = frozenset({"en", "ja"})


# ──────────────────────────────────────────────────────────────────────────────
# RagIngester class
# ──────────────────────────────────────────────────────────────────────────────
class RagIngester:
    """
    Embeds chunk files produced by ChunkSplitter and inserts them into SQLite.
    Each URL's chunks are processed as a group so they share one document record.
    After ingestion, chunk files are moved to rag-src/registered/.
    """

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        cfg: dict[str, Any] = config or ConfigLoader().load(
            "common.json", "rag_pipeline.json"
        )
        rag_src_dir = Path(cfg["rag_src_dir"])
        self._chunk_dir: Path = rag_src_dir / "chunk"
        self._registered_dir: Path = rag_src_dir / "registered"
        self._embed_url: str = cfg["embed_url"]
        self._embed_retry: int = int(cfg["embed_retry"])
        self._embed_workers: int = int(cfg.get("embed_workers", 4))
        self._client = httpx.Client(timeout=60)

    def close(self) -> None:
        """Close the underlying HTTP client."""
        self._client.close()

    def __del__(self) -> None:
        try:
            self._client.close()
        except Exception:
            pass

    # ── Public interface ──────────────────────────────────────────────────────

    def ingest_all(self, force: bool = False) -> None:
        """
        Process all chunk files in chunk_dir, grouped by URL.
        force=True deletes existing document records before re-inserting.
        """
        chunk_files = sorted(self._chunk_dir.glob("*.txt"))
        if not chunk_files:
            logger.info("No chunk files to process")
            return
        url_groups = self._group_chunks_by_url(chunk_files)
        with SQLiteHelper().open(write_mode=True) as db:
            self._process_url_groups(db, url_groups, force)
        logger.info(f"=== done: {len(url_groups)} URLs processed ===")

    def ingest_url_group(
        self, db: SQLiteHelper, url: str, chunk_files: list[Path], force: bool
    ) -> None:
        """
        Ingest all chunk files for one URL into SQLite in ascending chunk_index order.
        Moves chunk files to registered/ after processing (including on skip).
        """
        if not chunk_files:
            logger.warning(f"No chunk files provided for URL: {url}")
            return
        chunk_files = sorted(chunk_files, key=lambda p: p.stem)
        first_data = self._read_chunk_json(chunk_files[0])
        if first_data is None:
            return
        title: str = first_data.get("title", "")
        lang: str = first_data.get("lang", "en")
        etag: str | None = first_data.get("etag")
        last_modified: str | None = first_data.get("last_modified")
        doc_id = self._get_or_create_document(
            db, url, title, lang, force, etag, last_modified
        )
        if doc_id is None:
            logger.info(f"already registered, skipping: {url}")
            self._move_to_registered(chunk_files)
            return
        # Commit document record before parallel chunk inserts (FK dependency).
        db.commit()
        inserted = self._ingest_chunk_files(doc_id, chunk_files)
        logger.info(f"inserted {inserted}/{len(chunk_files)} chunks: {url}")
        self._move_to_registered(chunk_files)

    # ── Embedding ─────────────────────────────────────────────────────────────

    def _get_embedding(self, text: str) -> list[float] | None:
        """
        Send text to the embed-llm API and retrieve a 384-dimensional vector.
        multilingual-E5-small requires the "passage: " prefix for document ingestion.
        (Use the "query: " prefix at query time.)
        Returns None on failure or empty input, causing that chunk to be skipped.
        """
        if not text or not text.strip():
            return None
        for attempt in range(self._embed_retry):
            try:
                resp = self._client.post(
                    self._embed_url,
                    # E5 passage prefix is mandatory for document-side embedding
                    json={"content": f"passage: {text}"},
                )
                resp.raise_for_status()
                embedding = orjson.loads(resp.content).get("embedding")
                if not isinstance(embedding, list) or not embedding:
                    raise ValueError("missing or empty 'embedding' field in response")
                return embedding
            except (
                httpx.RequestError,
                httpx.HTTPStatusError,
                orjson.JSONDecodeError,
                ValueError,
            ) as e:
                logger.warning(
                    f"embedding attempt {attempt + 1}/{self._embed_retry}: {e}"
                )
                if attempt < self._embed_retry - 1:
                    time.sleep(min(2**attempt, 10))
        return None

    # ── Document helpers ──────────────────────────────────────────────────────

    def _delete_existing_document(self, db: SQLiteHelper, doc_id: int) -> None:
        """Delete a document and its chunks.
        chunks_vec is removed first because it has no FK constraint to chunks.
        """
        # Delete order: chunks_vec → chunks → documents
        # chunks_vec has no FK to chunks, so it must be removed explicitly first.
        db.execute(
            "DELETE FROM chunks_vec"
            " WHERE chunk_id IN (SELECT chunk_id FROM chunks WHERE doc_id = ?)",
            (doc_id,),
        )
        db.execute("DELETE FROM chunks WHERE doc_id = ?", (doc_id,))
        db.execute("DELETE FROM documents WHERE doc_id = ?", (doc_id,))

    def _update_etag(
        self,
        db: SQLiteHelper,
        doc_id: int,
        etag: str | None,
        last_modified: str | None,
    ) -> None:
        """Refresh ETag/Last-Modified for an existing document (skip-case)."""
        if etag is None and last_modified is None:
            return
        db.execute(
            "UPDATE documents SET etag = ?, last_modified = ? WHERE doc_id = ?",
            (etag, last_modified, doc_id),
        )

    def _get_or_create_document(
        self,
        db: SQLiteHelper,
        url: str,
        title: str,
        lang: str,
        force: bool,
        etag: str | None = None,
        last_modified: str | None = None,
    ) -> int | None:
        """Register a URL in the documents table and return its doc_id.

        Returns None if already registered and force=False.
        When force=False, refreshes etag/last_modified for the next conditional GET.
        When force=True, deletes the existing record before re-inserting.
        chunks_fts is auto-synced via the DELETE trigger (chunks_ad).
        """
        # Guard: reject lang values that violate the DB CHECK constraint early
        if lang not in _VALID_LANGS:
            raise ValueError(
                f"unsupported lang value: {lang!r}"
                f" (must be one of {sorted(_VALID_LANGS)})"
            )
        existing_row = db.execute(
            "SELECT doc_id FROM documents WHERE url = ?", (url,)
        ).fetchone()
        if existing_row:
            existing_doc_id: int = existing_row[0]
            if not force:
                # Refresh ETag/Last-Modified so the next crawl can use conditional GET
                self._update_etag(db, existing_doc_id, etag, last_modified)
                return None
            # force=True: remove old document (and its chunks) before re-inserting
            self._delete_existing_document(db, existing_doc_id)
        cur = db.execute(
            "INSERT INTO documents (url, title, lang, etag, last_modified)"
            " VALUES (?, ?, ?, ?, ?)",
            (url, title, lang, etag, last_modified),
        )
        return cur.lastrowid

    def _insert_chunk(
        self,
        db: SQLiteHelper,
        doc_id: int,
        idx: int,
        content: str,
        normalized_content: str | None,
        embedding: list[float],
    ) -> None:
        """
        Insert a chunk and its embedding vector into the database.
        chunks_fts is synced via the chunks_ai INSERT trigger using
        COALESCE(normalized_content, content), so FTS5 indexes normalized forms
        for Japanese chunks and falls back to raw content for others.
        Embedding stored as little-endian float32 BLOB (sqlite-vec MATCH requirement).
        """
        cur = db.execute(
            "INSERT INTO chunks (doc_id, chunk_index, content, normalized_content)"
            " VALUES (?, ?, ?, ?)",
            (doc_id, idx, content, normalized_content or None),
        )
        chunk_id = cur.lastrowid
        db.execute(
            "INSERT INTO chunks_vec (chunk_id, embedding) VALUES (?, ?)",
            (chunk_id, floats_to_blob(embedding)),
        )

    # ── Bulk file processing ──────────────────────────────────────────────────

    def _read_chunk_json(self, path: Path) -> dict[str, Any] | None:
        """Read and parse a chunk JSON file. Delegates to pipeline_utils."""
        return read_json_file(path)

    def _embed_and_store(self, doc_id: int, path: Path) -> bool:
        """Embed one chunk and insert it using an independent DB connection.

        Each call opens its own SQLiteHelper context so that concurrent threads
        do not share a single connection.  SQLite WAL mode serialises the actual
        writes while allowing the HTTP embedding calls to run truly in parallel.
        Returns True when inserted successfully, False otherwise.
        """
        data = self._read_chunk_json(path)
        if data is None:
            return False
        content: str = data.get("content", "")
        normalized_content: str | None = data.get("normalized_content") or None
        try:
            idx = int(data.get("chunk_index", 0))
        except (ValueError, TypeError) as e:
            logger.warning(f"Invalid chunk_index in {path.name}: {e}, using 0")
            idx = 0
        # Embed original content; E5 understands raw Japanese.
        # normalized_content is for FTS only and not used for embedding.
        embedding = self._get_embedding(content)
        if embedding is None:
            logger.warning(f"embedding failed for {path.name}: {content[:60]!r}")
            return False
        with SQLiteHelper().open(write_mode=True) as db:
            self._insert_chunk(db, doc_id, idx, content, normalized_content, embedding)
            db.commit()
        return True

    def _ingest_chunk_files(self, doc_id: int, chunk_files: list[Path]) -> int:
        """Embed and insert chunk files in parallel. Returns count of inserted chunks.

        Uses ThreadPoolExecutor so that embed_workers HTTP calls run concurrently.
        DB inserts inside each worker are committed with independent connections.
        """
        inserted = 0
        with ThreadPoolExecutor(max_workers=self._embed_workers) as executor:
            futures = {
                executor.submit(self._embed_and_store, doc_id, path): path
                for path in chunk_files
            }
            for future in as_completed(futures):
                path = futures[future]
                try:
                    if future.result():
                        inserted += 1
                except Exception as e:
                    logger.error(f"Failed to ingest {path}: {e}")
        return inserted

    def _group_chunks_by_url(self, chunk_files: list[Path]) -> dict[str, list[Path]]:
        """Group chunk files by URL read from their JSON 'url' field."""
        url_groups: dict[str, list[Path]] = defaultdict(list)
        for path in chunk_files:
            data = self._read_chunk_json(path)
            if data is None:
                continue
            url: str = data.get("url", "")
            if not url:
                logger.warning(f"url field missing: {path.name}")
                continue
            # Accept file:// URLs from local file ingestion in addition to http/https
            if not validate_url(url) and not url.startswith("file://"):
                logger.warning(f"invalid url {url!r} in {path.name}, skipping")
                continue
            url_groups[url].append(path)
        return url_groups

    def _process_url_groups(
        self,
        db: SQLiteHelper,
        url_groups: dict[str, list[Path]],
        force: bool,
    ) -> None:
        """Iterate over URL groups and ingest each; log exceptions without stopping."""
        for url, paths in url_groups.items():
            try:
                self.ingest_url_group(db, url, paths, force)
            except Exception:
                logger.exception(f"ingest_url_group failed: {url}")

    def _move_to_registered(self, paths: list[Path]) -> None:
        """Move ingested chunk files to registered/."""
        self._registered_dir.mkdir(parents=True, exist_ok=True)
        for path in paths:
            dest = self._registered_dir / path.name
            try:
                shutil.move(str(path), str(dest))
            except OSError as e:
                logger.error(f"move failed {path} → {dest}: {e}")


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Embedding generation and DB ingestion:"
            " rag-src/chunk/*.txt → SQLite → rag-src/registered/"
        )
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Force delete and re-ingest already registered URLs",
    )
    args = parser.parse_args()

    ingester = RagIngester()
    ingester.ingest_all(args.force)


if __name__ == "__main__":
    main()
